### ISSUE TITLE
Initial feedback

### ISSUE THREAD

**Issue by tundrablasen** [ivarbrandt/skin.FENtastic#1]
Sounds perfect! Just installed it and it seems it works perfect. But ofc I need to daily drive it. Some tips and initial feedback:

1. I would do an announcement post in the addons4kodi subreddit. Will give you some traction. People waited for fentastic.
2. define a space for bug report/feedback. Issue section of your GitHub? Or in Reddit? Etc
3. the episodes view for widgets is awesome. Perfect for the „next episodes“ widget
4. PLEASE disable the intro music when starting kodi. It’s way to loud (my kid slept next to me when I started it for the first time and now it’s awake), and also not everybody is a fan of drum and bass. if music at all it should be a super short, and gentle jingle sound. Or at least make it optional.
5. is the video on start up necessary? (does it have a purpose? is something loading in the background and you want to cover waiting times with that?)

Question: the widgets load ultra fast on my shield tv. How much items per widget row gets loaded initially? It’s really fast and cool

Keep up the good work. And thanks for this great FEN addition.

**Comment by ivarbrandt** [comment]
Thanks for your feedback! I'm glad you like it. It's been my daily driver for awhile so please keep me posted on your experience.

> I would do an announcement post

I'm gonna hold off on making an announcement post on Reddit. Just for a little bit.

> PLEASE disable the intro music

Done. I'm sorry the intro video woke your kid. I hope they were able to go back to sleep quickly.

> is the video on start up necessary?

It's not necessary. I just really like it over a static splash screen. That being said I did notice some funny business with the widgets when the startup video was disabled. I'll look into that soon.

> the widgets load ultra fast on my shield tv

Oh yeahhh they do 😉 

> How much items per widget row gets loaded initially?

There are up to 21 movie/show items per row, 10 episode items per row, and 50 category items on the top and bottom.

I have a question for you as well. When you first loaded the skin and you saw the small dialog pop up explaining how to set up the widgets and menu items, did it load some widgets automatically after you hit OK? Or were the Movie and Show sections empty on the home screen?

**Comment by tundrablasen** [comment]
I did not install your skin on a vanilla kodi instance.

i have jellyfin on my NAS installed and that populates the kodi video library. 

There after installing your skin I saw directly my video library.

i had to go to setting and first set up my widgets which pointed to fen. 

After that I saw my fen widgets

**Comment by ivarbrandt** [comment]
Perfect! That's exactly the way it's supposed to work.
