### ISSUE TITLE
Feature Request - Title in widget

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.FENtastic#10]
Hi again,

On "Shows" menu - I want to add TV Shows Networks list widget. (Fen --> TV Shows --> Networks).
(My end goal will be to add Shortcut Menu of my custom choose Networks, but for the example I'll use the full list.)

I've added the 3 widgets type for comparison - Poster/Landscape/Episode.
Screenshot:

![image](https://user-images.githubusercontent.com/29895680/229622160-d675c623-9e7c-43d3-a248-92513590a98a.png)

I think the best fits for them is "Episode" view, the network icon looks the best. 
Only missing for me is the Network title below the logo, **as for example shown here in Movies --> Trending (Episode View)**:
![image](https://user-images.githubusercontent.com/29895680/229625717-0ce5aa27-3e4c-47eb-a245-98b4d3f42a72.png)

Or in TV Shows --> Trending (Episode View):
![image](https://user-images.githubusercontent.com/29895680/229623023-70086e73-82d8-4574-9972-9a8f10420c1a.png)

If you don't want to override current existing 3 views, maybe if possible to add more view types to the skin? (Episode view w/ title, etc..)

Thank you very much!

**Comment by ivarbrandt** [comment]
This is a good idea. I was thinking about looking into this. However it's not something I want to do right now as my focus is elsewhere.

**Comment by TwilightMercy** [comment]
No problem, keep me updated here when you’ll can 🙏🏻

**Comment by ivarbrandt** [comment]
I'm beginning to work on this.

Which image do you prefer?

TOP
![Screen Shot 2023-04-07 at 10 32 11 AM](https://user-images.githubusercontent.com/54084201/230644779-4bbf01c6-dfee-4bab-848d-e9a5a4214ac0.png)

BOTTOM
![Screen Shot 2023-04-07 at 10 33 33 AM](https://user-images.githubusercontent.com/54084201/230644817-dc9f2862-77f7-4eed-87f8-3bb082522e24.png)

**Comment by ivarbrandt** [comment]
Completed for next update.

**Comment by TwilightMercy** [comment]
You’re the best!

**Comment by TwilightMercy** [comment]
Works great
