### ISSUE TITLE
Skin missing from repository 

### ISSUE THREAD

**Issue by ReverseBass** [ivarbrandt/skin.fentastic#100]
Hello, 

After installing from zip I go to install from repository, however there is no skin section in the "look and feel" category. I only have one item that says "GUI sounds" 

Tried reinstalling repository and rebooting firestick. 

Thanks!

**Comment by ivarbrandt** [comment]
Try it now.

**Comment by ReverseBass** [comment]
Still no luck. I thought the issue was that I was using Omega but uninstalled Kodi and am using Nexus 20.5 now.

**Comment by ivarbrandt** [comment]
The skins were updated to work with Omega. The reasons you couldn't see them before is because they hadn't been updated yet to work with Omega.

Try going back to Omega and you should be good to go.

**Comment by ReverseBass** [comment]
Works on Omega! Thank you!

**Comment by ivarbrandt** [comment]
You're welcome!

**Comment by spookymulder88** [comment]
I have the same problem, but on android, with the kodi version 20.5.

**Comment by TwilightMercy** [comment]
> I have the same problem, but on android, with the kodi version 20.5.

Upgrade to 21.0 Omega

**Comment by spookymulder88** [comment]
Its the newest version on android. Omega there is not released. So i have to wait

**Comment by spookymulder88** [comment]
Now it works
