### ISSUE TITLE
Kodi Omega 21 Freezes on Startup Xbox Series S and Xbox One S

### ISSUE THREAD

**Issue by KweenMother** [ivarbrandt/skin.fentastic#104]
Here is a clear and concise description of what the problem is:

Kodi Omega 21 installed on Xbox Series S and Xbox One S, connected to Yaber Y30 projector, Samsung TV and TCL TV
Kodi with Fentastic, Fen Light, The Crew, YouTube and Trakt. Using Real Debrid and All Debrid. 

Whenever I start up Kodi on any Xbox (2 Xbox Series S's and 1 Xbox One S) it freezes and you must quit Kodi and restart, or it crashes and takes you back to Xbox home screen. The issue will happen again on restart. The only option is to select a different tab while Kodi is loading, such as "Add-on" or "TV Shows". Only Moving the "cursor" around seems to stop Kodi from freezing upon startup.
I don't know if it's how I configured the skin, a setting, or add-on

Expected Behavior:
For Kodi to start and load widgets

Actual Behavior:

Kodi freezes and you must quit and restart. Or kodi crashes and takes you back to xbox home screen.

Possible Fix:

If you select another tab while Kodi is loading widgets it won't freeze. If you select "TV Shows" or "Addons" while Kodi is loading, 90% of the time Kodi won't freeze.

I'm not too familiar with reading and posting logs but I've attached a log below (I think.)
https://paste.kodi.tv/awobekenin

I've googled this issue for several months and played with different settings, but I'm still no closer to a solution.

Thanks for your time,
-Mother

**Comment by KweenMother** [comment]
Error in copying the log link. It should be:
https://paste.kodi.tv/awobekenin

**Comment by ivarbrandt** [comment]
I recommend trying to see if you have the same issues on Estuary (the default Kodi skin). If you do, you could try deleting the addons13.db file located in userdata/Database. And then reenable each addon manually after that. Sometimes, the databases get corrupted and deleting this file normally fixes just about anything that may be wrong with your Kodi.
