### ISSUE TITLE
Issue - "Shows" Menu isn't translated to Hebrew

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.FENtastic#11]
Hi,

Not sure if this is Kodi issue, or FENtastic specific.. : )

I'm using Hebrew language in Kodi. the "Menu" and "Shows" menu in English are shown as:
![image](https://user-images.githubusercontent.com/29895680/229623831-8e6a9a0b-1e9f-4b10-8b00-df4c40a9de3f.png)

And in default Estuary skin, in Hebrew Language it looks like:

![image](https://user-images.githubusercontent.com/29895680/229623993-207accb8-a926-4a40-80a5-c853db3eb9c2.png)

When Hebrew language is set with FENtastic skin, only "Movies" is translated to Hebrew, and "Shows" stays in English.

![image](https://user-images.githubusercontent.com/29895680/229624202-021b735d-9720-4c56-a1c6-ce03c36d92c5.png)

I'm not sure if log is needed, if so let me know.

Thanks!

**Comment by ivarbrandt** [comment]
This is FENtastic specific and cannot be changed via the skin. I can be changed if you're willing to dive into the code.

If you are, go to addons, script.FENtastic.helper, resources, modules, xmls.py

On line 67, change `<label>Shows</label>` to `<label>$LOCALIZE[20343]</label>`

Save it, then go back into Skin settings and click Remake menus and widgets. 

This will fix your concern. Keep in mind that you'll have to do this every time a new update gets released for the FENtastic Helper.

**Comment by TwilightMercy** [comment]
Thank you. 

If the Movies menu is localized, why won’t be Shows also?

![image](https://user-images.githubusercontent.com/29895680/229972188-b7912a34-7a27-4032-b67c-e2f1fff5fa96.png)

**Comment by ivarbrandt** [comment]
https://kodi.wiki/view/Label_Parsing

The "TV shows" label that is in `<label>$LOCALIZE[20343]</label>` isn't located in the skin. It's located somewhere else in Kodi. Otherwise I would just change the US version of strings.po to "Shows" and that would leave all other languages untouched.

**Comment by TwilightMercy** [comment]
I have no problem to manually change it, and update script.FENtastic.helper once in a while and re-edit xmls.py,

But there is no way from your side to use LOCALIZE also for Shows, for it to work for other languages?

**Comment by ivarbrandt** [comment]
No there isn't. Because the LOCALIZE label for Shows is located somewhere else outside of the skin.

**Comment by TwilightMercy** [comment]
The same also for Movies?

**Comment by ivarbrandt** [comment]
Correct.

**Comment by TwilightMercy** [comment]
Update:
I changed xmls.py in script.FENtastic.helper as you instructed and it works!

![image](https://user-images.githubusercontent.com/29895680/230237943-494e66e5-f948-4a3d-b854-70d0138b1b96.png)



Sorry if I'm annoying with issues lately, I couldn't understand why "Movies" is configured with LOCALIZE and works great with Hebrew, and why Shows couldn't.

Thanks for the help! : )

**Comment by ivarbrandt** [comment]
Good job! Glad you were able to figure it out.

**Comment by ivarbrandt** [comment]
As of `1.0.12a` FENtastic will use the default $LOCALIZE string as the label for Movies and TV Shows if you enter an empty string when clicking Rename on a main menu item. You can of course change the label yourself to whatever you'd like, but the default will be what you wanted in the previous messages. Also, the labels that you set for the main menu items will be reflected in Skin settings as well.
