### ISSUE TITLE
Clearing a category widget

### ISSUE THREAD

**Issue by CaptainMoody** [ivarbrandt/skin.FENtastic#12]
Hi,

Great job on the new skin - I have finally been able to replace my bloated AH2 setup with something much slicker and simpler to navigate.
Last night I decided to set up a top category widget for TV Shows but I mistakenly set it up in movies, now I cannot find any way to remove the wrong widget. I can change the widget to something else or disable category widgets completely but I cannot remove it.

Thanks.

**Comment by ivarbrandt** [comment]
You are right. You can't clear a category widget. I've never had to do this so I didn't even consider adding that functionality.

I will look into adding this when I get a chance. 

In the meantime, you can go to userdata/addon_data/script.FENtastic.helper and then delete the cpath_cache.db file. Then click Remake and menus and widgets in Skin settings. This will delete all of your widgets so you'll have to set them up again.
It will fix your issue though.

**Comment by ivarbrandt** [comment]
I've decided I won't be adding this in because the path can be changed and that will rewrite the category widget. If you don't want to use category widgets you can disable them like you said.

**Comment by ivarbrandt** [comment]
As of v1.0.8, you can now clear category widgets.
