### ISSUE TITLE
[Question] Refresh Widgets Menu Option

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.FENtastic#14]
Hi,

I've noticed that "Refresh Widgets" in context menu only appears on "Movies" menu widgets. In Shows widgets it doesn't show.

And what's the difference between "Refresh Widgets" and "Reload Skin" from power button?

![image](https://user-images.githubusercontent.com/29895680/230501037-94d61570-2c34-41f6-a735-f89abf49e0c2.png)

Thanks!

**Comment by ivarbrandt** [comment]
> I've noticed that "Refresh Widgets" in context menu only appears on "Movies" menu widgets. In Shows widgets it doesn't show.

This is a Fen thing so you'll have to talk to TIkipeter about it. That being said, I'm seeing 'Refresh Widgets' for tvshows in the Options window..

> And what's the difference between "Refresh Widgets" and "Reload Skin" from power button?

'Refresh Widgets' is for Fen. Let's say you added something to your Watchlist and it hasn't showed up yet on your Watchlist widget. If you click 'Refresh Widgets', it will force the refreshing of the widgets so the item you added will show up.. 

'Reload skin' is for the skin. I use this for developing purposes but you don't really need to use it as the skin will automatically reload when you change/add widgets etc

**Comment by TwilightMercy** [comment]
> > I've noticed that "Refresh Widgets" in context menu only appears on "Movies" menu widgets. In Shows widgets it doesn't show.
> 
> This is a Fen thing so you'll have to talk to TIkipeter about it. That being said, I'm seeing 'Refresh Widgets' for tvshows in the Options window..
> 
> > And what's the difference between "Refresh Widgets" and "Reload Skin" from power button?
> 
> 'Refresh Widgets' is for Fen. Let's say you added something to your Watchlist and it hasn't showed up yet on your Watchlist widget. If you click 'Refresh Widgets', it will force the refreshing of the widgets so the item you added will show up..
> 
> 'Reload skin' is for the skin. I use this for developing purposes but you don't really need to use it as the skin will automatically reload when you change/add widgets etc

I see.

That's another question I wanted to ask - I've set a widget of Fen Favorites, and when adding a movie to it - it doesn't appear in the widget immediately - only after "Refresh Widget".
Is it possible to somehow automatically refresh widgets after those actions? Another example:
I have Category widget set for Search. I search some movie, and go back to skin - the search doesn't show up in history immediately .

**Comment by ivarbrandt** [comment]
> Is it possible to somehow automatically refresh widgets after those actions?

Again, this is a question for the Fen dev. I could add a skin timer to make it refresh more often but I decided against that because that will be hard on resources. Also, I'm pretty sure if you add something from inside the addon, then go to a widget, it will refresh almost instantly.

> I search some movie, and go back to skin - the search doesn't show up in history immediately

Try using the built in search from the home menu. Those shortcuts point directly to the Fen so they update instantly.

**Comment by TwilightMercy** [comment]
Thank you for the info!
you can close : )

**Comment by ivarbrandt** [comment]
You're welcome 👍
