### ISSUE TITLE
[Enhancement Request] Align plot text to right for Hebrew language

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.FENtastic#15]
Hi,

I have small request/question - if it's not possible and too burden to do, don't mind investing time into it.

By default, in InfoPanel of the movie synopsis, release details, etc is written in Left To Right (LTR) direction in English:
![image](https://user-images.githubusercontent.com/29895680/230626203-a29fbca2-d513-4d67-adac-4ab7f31c153a.png)

In Hebrew language configured in settings of Kodi + Fen Metadata - is it possible to make the text direction RTL? (based on skin option if not language-automatic)
Current example in Hebrew: (LTR instead of RTL)

![image](https://user-images.githubusercontent.com/29895680/230626522-4020fbbf-667c-4dcc-9ee0-17de538881d7.png)

**Comment by ivarbrandt** [comment]
Is the tagline and plot reading from RTL?

**Comment by TwilightMercy** [comment]
> Is the tagline and plot reading from RTL?

In Hebrew yes
In English LTR

**Comment by ivarbrandt** [comment]
Do you want the information like Genre, Director etc to read RTL as well?

**Comment by TwilightMercy** [comment]
> Do you want the information like Genre, Director etc to read RTL as well?

Yes : )

**Comment by ivarbrandt** [comment]
It looks like it's reading RTL. How is it not?

Keep in mind I don't know the language.

**Comment by TwilightMercy** [comment]
> It looks like it's reading RTL. How is it not?
> 
> Keep in mind I don't know the language.

Correcting myself:
I'm using the Alternate InfoPanel, so the top stuff (Releasd, Genre, Director, End Time) - Keep it the same.

And the movie synopsis:
My bad, I mean the text is written correctly - I meant to use the word "alignment" instead of RTL, in Hebrew the text is aligned to the right. example in arrows:

![image](https://user-images.githubusercontent.com/29895680/230676525-3ba8b337-bc62-4c05-bdb5-b94137cc6619.png)

**Comment by ivarbrandt** [comment]
Ok I think I understand what you're talking about.

Something like this?

![Screen Shot 2023-04-07 at 3 25 02 PM](https://user-images.githubusercontent.com/54084201/230681160-3faec32b-8b56-4622-9abe-8c44185af085.png)

**Comment by TwilightMercy** [comment]
> Ok I think I understand what you're talking about.
> 
> Something like this?
> 
> ![Screen Shot 2023-04-07 at 3 25 02 PM](https://user-images.githubusercontent.com/54084201/230681160-3faec32b-8b56-4622-9abe-8c44185af085.png)

Change you change Kodi language + Fen Metadata language to Hebrew and screenshot? so I can verify 100%

**Comment by ivarbrandt** [comment]
No I won't do that because Fen will erase my metacache and I'll lose all of my custom artwork.

I'm pretty sure it's what you're asking for. I can't do anything about the actual language but the text aligns itself to the right if you have the Hebrew language selected in Kodi.

You'll have to wait for the next update to verify for yourself.

**Comment by TwilightMercy** [comment]
> No I won't do that because Fen will erase my metacache and I'll lose all of my custom artwork.
> 
> I'm pretty sure it's what you're asking for. I can't do anything about the actual language but the text aligns itself to the right if you have the Hebrew language selected in Kodi.
> 
> You'll have to wait for the next update to verify for yourself.

Great that's what i ment, if the langauge is Hebrew to the text alignemnt the right is perfect.
From the screenshot you sent it aligns the whole text, if possible - only for the bottom text (movie synposis)

**Comment by ivarbrandt** [comment]
No, that requires me change the whole InfoPanel. I'm not going to do that.

**Comment by TwilightMercy** [comment]
> No, that requires changing the whole InfoPanel.

I see, no problem keep it that way : )

**Comment by ivarbrandt** [comment]
Completed for next update.

**Comment by TwilightMercy** [comment]
Works perfect on Hebrew!

**Comment by TwilightMercy** [comment]
Hi friend, 

Is it possible to re-open this issue and add to it? I missed something from my previous request.

Right now, if the language in Kodi is Hebrew - the movie/show InfoPanel text is aligned to the right. It works perfect.
Back when I requested this, I was with FEN setting : `Metadata --> Enable Extra Art - Enabled`

![image](https://user-images.githubusercontent.com/29895680/233780570-f8540d19-3d72-4864-8774-f37302812271.png)

So for each movie/show title, I would see it's Logo. Example for "Ant-Man and the Wasp: Quantumania" Movie:
![image](https://user-images.githubusercontent.com/29895680/233780695-2dfe98b6-5274-4655-81b7-7e4b56eede80.png)


Now I switched **Enable Extra Art** settings to OFF in my build. So - if the movie/show already have Hebrew Logo it shows up. but if it doesn't - it shows the title itself as text:
![image](https://user-images.githubusercontent.com/29895680/233781110-26a595a9-7626-445b-afaf-0a962e3172b1.png))


Can the title also be aligned to the right, for Hebrew language in Kodi? (In addition to InfoPanel plot details)

Thanks!

**Comment by ivarbrandt** [comment]
I'm not sure if this is possible without making bigger changes to the skin. That being said, I will do my best to implement it in the next update.

**Comment by TwilightMercy** [comment]
Yes it works! :)


```
					<control type="textbox">
						<top>75</top>
						<left>10</left>
						<width>430</width>
						<aligny>center</aligny>
						<height>98</height>
						<font>font36_title</font>
						<label>$INFO[ListItem.Label]</label>
						<visible>String.IsEmpty(ListItem.Art(clearlogo)) + !String.IsEqual(System.Language,Hebrew)</visible>
					</control>
					<control type="textbox">
						<top>75</top>
						<left>10</left>
						<width>430</width>
						<aligny>center</aligny>
						<height>98</height>
						<font>font36_title</font>
						<align>right</align>
						<label>$INFO[ListItem.Label]</label>
						<visible>String.IsEmpty(ListItem.Art(clearlogo)) + String.IsEqual(System.Language,Hebrew)</visible>
					</control>
```

**Comment by ivarbrandt** [comment]
Good! I'll add it for next update.

**Comment by TwilightMercy** [comment]
Hi friend,

I wanted to ask for the reason of [this commit](https://github.com/ivarbrandt/skin.fentastic/commit/c1486293296d46ed38b5d52160124961a5070ac0) changes, specifically for `removed language specific labels/textboxes` - The removal of:

```
<visible>String.IsEqual(System.Language,Hebrew)</visible>
<align>right</align>
```

For these files:

```
Custom_1121_SearchResults.xml
Home.xml
MyVideoNav.xml
View_50_List.xml
```

Still being used until today 😅

**Comment by ivarbrandt** [comment]
Yes, I figured that now that you and your group has a fork of my skin, I could remove the language specific sections since I don't use them at all.

**Comment by TwilightMercy** [comment]
True, when I pulled the latest test version from your repo to my fork, it removed it, but I brought it back manually, so all good : )
Thanks again for everything

**Comment by ivarbrandt** [comment]
Makes sense. That's why I have my code visible. So anyone can go back and find the changes they didn't like and then revert them in their own fork.

Also, keep in mind that if you don't like the new UI changes, I have version `1.0.13c` available in the test repo that has everything from before all of the UI changes.

**Comment by TwilightMercy** [comment]
> Also, keep in mind that if you don't like the new UI changes, I have version `1.0.13c` available in the test repo that has everything from before all of the UI changes.

On the contrary, all the UI changes are really great. Now default Estuary skin design feels really old.
I liked all of them (except specifically `DialogContextMenu.xml` which I used `1.0.13c` version to see the whole list)

A little off-topic, I did (with some help of a skin developer friend) some additions to FENtastic in my fork. If you want me to open a separate issue for it, to take some ideas, sure. Sharing some screenshots:

Poster View:
* Top of screen - Content art logo
* Label - yellow color
* Added "Genre" above the plot section
* Bottom of screen - added rating, release data, length, studio name
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/cbeffa27-8716-4bc4-99ec-90e8dc3d7263)

InfoPanel:
* Added studio/network variable
* Changed variables names to Bold
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/d8e59c14-d265-45e5-ae73-a468038c5dc6)

InfoPanelEpisode:
* Added episode length and EndTime
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/ab9a91c2-4817-48a7-9c97-2963f8822157)


And there's some more adjustments to VideoOSD.xml and some more, that's the main things : )

**Comment by ivarbrandt** [comment]
Very cool! Glad you've been able to change it to your liking.

**Comment by TwilightMercy** [comment]
-Edited with addition of player OSD-

Thank you, it's really great : )

**Comment by ivarbrandt** [comment]
The OSD looks mad clean. I've been wanting to modify the OSD but I haven't decided what I want it to look like.

**Comment by TwilightMercy** [comment]
I agree : ) The media flags are really clean and really improving the OSD experience

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/6d146fc0-9043-43b7-a8d0-577c500a99cb)

for the top logo of the Network , It works but I had a small issue with it to make it work for any available network that is given from `$INFO[VideoPlayer.Studio]` variable, something that requires a small code addition to helper. If that's ok to ask for your help with it I'll open a separate issue.

------------------------------------------------------------------------------------------------------------------------------------------

About the Hebrew language support, I currently use in my fork the original code you had, example:

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/0f84163c-4ef7-4e2b-8c9e-59d1fdce07af)

I thought of maybe making the code for all duplicate controls (one without align setting, and the other with align right, based on language condition) - and to combine them to one control (like in your current code after the removal).

I tried to create a variable in `Variables.xml`:
```
<variable name="SetAlignDirection">
	<value condition="String.IsEqual(System.Language,Hebrew)">right</value>
	<value condition="!String.IsEqual(System.Language,Hebrew)">left</value>
</variable>
```

Or as another option for the variable:
```
<variable name="SetAlignDirection">
	<value condition="String.IsEqual(System.Language,Hebrew)">right</value>
	<value>left</value>
</variable>
```

And then use one control only with the align paramter (without `<visible>` condition):
```
<control type="textbox">
	<!-- some code -->
	<align>$VAR[SetAlignDirection]</align>
	<label>$INFO[ListItem.Label]</label>
</control>
```
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/7bb29807-bbbb-4192-ba91-557d3081ab08)

But it didn't work - is always aligned to left side, no matter Kodi language.
Did I did something wrong?

Thank you very much!

**Comment by TwilightMercy** [comment]
@ivarbrandt

**Comment by ivarbrandt** [comment]
Yes?

**Comment by ivarbrandt** [comment]
I didn't see you had asked for my help. I apologize.

What you are trying to do is not possible because variables can't be assigned to align values as these are designed to be static. You could create  an include and then call that. Here's what it would look like:

`Includes.xml`

          
```
<include name="InfoPanel">
        <control type="textbox">
	        <visible>!String.IsEqual(System.Language,Hebrew)</visible>
	        <left>30</left>
	        <top>239</top>
	        <width>410</width>
	        <bottom>60</bottom>
	        <label>$VAR[InfoPanel]</label>
	        <autoscroll delay="10000" time="3000" repeat="10000">Skin.HasSetting(autoscroll)</autoscroll>
        </control>
        <control type="textbox">
	        <visible>String.IsEqual(System.Language,Hebrew)</visible>
	        <left>30</left>
	        <top>239</top>
	        <width>410</width>
	        <bottom>60</bottom>
	        <align>right</align>
	        <label>$VAR[InfoPanel]</label>
	        <autoscroll delay="10000" time="3000" repeat="10000">Skin.HasSetting(autoscroll)</autoscroll>
        </control>
</include>
```


Then call your new include where the textbox for the InfoPanel used to be in `Home.xml`:

`<include content="InfoPanel"/>`

**Comment by TwilightMercy** [comment]
I see, good approach:) thanks for the help!
