### ISSUE TITLE
[Issue] Changelog Window is empty for any Add-on

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.FENtastic#17]
Hi,

For some reason in FENtastic, when clicking on changelog window in any add-on, it's always empty. on Estuary skin it isn't.
If log is needed, tell me I will send.
This is happening for any add-on.

**Screenshots examples:**
![image](https://user-images.githubusercontent.com/29895680/230725712-18770405-745e-487b-9e2f-cd292d682554.png)

![image](https://user-images.githubusercontent.com/29895680/230725722-4934fdbf-7a8d-44dc-b802-6a032aed3f28.png)

**Comment by ivarbrandt** [comment]
Yes, you observed correctly.

**Comment by ivarbrandt** [comment]
I have added this back in for next update.
