### ISSUE TITLE
[Issue] Kodi crashes after stopping playback

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.FENtastic#18]
Hi,

If this issue is more relevant to Tikipeter, tell me and I'll re-open the issue to him. However, from my testing, it doesn't happen on basic Estuary skin, only with FENtastic.

At first, I thought it's only one time bug, because it didn't happen to me again for a while. And today it happened again, and also to my friend on his device.

Device: Android TV (Mine: MECOOL KM2 Plus)
Issue: "Fen Error" popup (red color) and then Kodi crashes.
When: After stopping playback of movie/show, and then going back from the episodes/movie screen to home screen.

Log is attached:
https://pastebin.com/raw/wXdk9JUY
Relevant last lines in log:
```
2023-04-11 22:20:14.702 T:13827   error <general>: EXCEPTION: Kodi is not playing any media file
2023-04-11 22:20:14.751 T:13685    info <general>: CPythonInvoker(36, /storage/emulated/0/Android/data/kodirdil20.xbmc.kodi/files/.kodi/addons/plugin.video.fen/resources/lib/fen.py): waiting on thread 3053961664
2023-04-11 22:20:16.044 T:13264   error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2023-04-11 22:20:24.804 T:13994   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: __import__ not found
                                                   -->End of Python script error report<--
```

Edit: adding a log from my friend who had the crash again:
https://pastebin.com/raw/0MCqGkY1
He has a different log:
```
2023-04-12 15:18:03.731 T:15045   error <general>: Control 55 in window 10001 has been asked to focus, but it can't
2023-04-12 15:18:05.128 T:15420 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
```

**Comment by ivarbrandt** [comment]
First, don't open an issue on Tikipeter's github because I have already called this to his attention and he said he's looking into it. In fact, there is an issue open there already that mentions this kind of behavior.

> However, from my testing, it doesn't happen on basic Estuary skin, only with FENtastic.

This behavior isn't confined to just FENtastic. It seems to be happening on any skin that has widgets. Other people have had the same issue with Arctic Horizon 2 and other skins. It doesn't happen on default Estuary because that skin doesn't have widgets.

Now as for a solution, the dev of Fen is working on that. We just have to relax while he does his thing. 

I personally don't have an issue with it crashing from time to time. If you do, you could try disabling the Reuse Language Invoker in Fen. This will make Fen a little bit slower when navigating but it might solve your crash issues.

**Comment by TwilightMercy** [comment]
> First, don't open an issue on Tikipeter's github because I have already called this to his attention and he said he's looking into it. In fact, there is an issue open there already that mentions this kind of behavior.
> 
> > However, from my testing, it doesn't happen on basic Estuary skin, only with FENtastic.
> 
> This behavior isn't confined to just FENtastic. It seems to be happening on any skin that has widgets. Other people have had the same issue with Arctic Horizon 2 and other skins. It doesn't happen on default Estuary because that skin doesn't have widgets.
> 
> Now as for a solution, the dev of Fen is working on that. We just have to relax while he does his thing.
> 
> I personally don't have an issue with it crashing from time to time. If you do, you could try disabling the Reuse Language Invoker in Fen. This will make Fen a little bit slower when navigating but it might solve your crash issues.

I see, thank you very much for the explanation.

1. Can you send me link to the open issue in Tikipeter's github? just so I can read there and follow there also.

2. Can you explain me what is the purpose of "Reuse Langauge Invoker", how does it solve the crash issues, and how do I disable it? (via Kodi GUI / Fen files?)

Thank you very much!

**Comment by ivarbrandt** [comment]
> Can you send me link to the open issue in Tikipeter's github?

I'll post the link here when his Issues open back up again.

> Can you explain to me what is the purpose of "Reuse Langauge Invoker", how does it solve the crash issues

It was a new feature introduced in Kodi 18 Leia. You can find more info by googling it. Just know that anything from the Kodi forum or Wiki isn't available for viewing right now as they are recovering from a data breach.

> and how do I disable it?

Go into the Fen addon > Tools > click **TOOLS:** Set Language Invoker (ADVANCED!!) > Set it to FALSE

**Comment by TwilightMercy** [comment]
Thank you very much, I disabled "Reuse Langauge Invoker" and I see immediate improvement, also on Windows PC!

**Comment by TwilightMercy** [comment]
> Thank you very much, I disabled "Reuse Langauge Invoker" and I see immediate improvement, also on Windows PC!

I would recommend adding a note about it in FENtastic Extra Info, since FEN comes with it enabled by default.

**Comment by TwilightMercy** [comment]
Thanks! you can close the issue :)

**Comment by ivarbrandt** [comment]
> Can you send me link to the open issue in Tikipeter's github?

https://github.com/Tikipeter/repository.tikipeter/issues/199#issuecomment-1484345265
