### ISSUE TITLE
Episode widget limit 

### ISSUE THREAD

**Issue by IG2022** [ivarbrandt/skin.FENtastic#2]
Hey there I found your skin over in the Tikipeter repository and decided to try it out. I'm really impressed with what you've done, it looks and works great for the short time I've used it. Thanks for putting this together for other Fen users.

I had a request for you if you don't mind. I know you may be busy still trying to get everything sorted out but I was hoping that you could increase the widget limit for episodes, right now it's 10 and alot of the shows in my next episode widget are missing. 

Again thanks alot for working on this I'm sure alot of people will appreciate it once it starts to get some traction!

**Comment by ivarbrandt** [comment]
Thank you for the kind words. I'm glad you're enjoying it.

I have added widget limits in the next update. You'll find them near the top of the General section of Skin settings.

**Comment by IG2022** [comment]
> Thank you for the kind words. I'm glad you're enjoying it.
> 
> I have added widget limits in the next update. You'll find them near the top of the General section of Skin settings.

Thanks alot for adding that in! Looking forward to the next update.

**Comment by tundrablasen** [comment]
Please leave the default limit where it is right now. Because I really prefer speed over many items in widgets. Since they are anyway loading super fast, as soon as you navigate to them.

raising the episode limit by default makes the whole thing slower

**Comment by IG2022** [comment]
I Just saw the update. Thank you so much for sorting this out. The skin feels extremely fast and works really well ive had no issues. Keep up the great work!

**Comment by ivarbrandt** [comment]
@tundrablasen 

> Because I really prefer speed over many items in widgets.

Same here. The default will stay at 10. I just added the option to adjust them. You could set the limits lower to make it even faster if you want. 

@IG2022 

Great! Glad to hear it's working well for you. Thanks for your feedback.
