### ISSUE TITLE
Randomizing trakt lists 

### ISSUE THREAD

**Issue by geeki0s** [ivarbrandt/skin.FENtastic#20]
Just trying this one out and it's brilliant. Still tinkering.

Question: Is there an option to randomize my widget without resorting to TMDB helper's random section?

**Comment by ivarbrandt** [comment]
Fen can display random movies and tvshows from your Trakt collection. You can point your widget to My Lists > **TRAKT:** Collection > and there you'll see Random Movies and Random TV Shows.

**Comment by geeki0s** [comment]
Thanks for the tip!

**Comment by ivarbrandt** [comment]
You're welcome!
