### ISSUE TITLE
Widget bug

### ISSUE THREAD

**Issue by Dappakid13** [ivarbrandt/skin.fentastic#21]
I have 1 category widget (not stacked) and 9 other widget (poster). The 10th one on both tv shows and movies always appear at the top instead of the bottom. I have attached some pics of a random widget I was testing.
![20230506_182632](https://user-images.githubusercontent.com/54221932/236650298-ad53f03e-d782-434b-a00b-1a0c8cfe084b.jpg)
![20230506_182515](https://user-images.githubusercontent.com/54221932/236650299-9c190388-4655-4da1-8d54-a86b65fe9539.jpg)

**Comment by ivarbrandt** [comment]
That is strange. Is this happening just on the 10th widget?

**Comment by Dappakid13** [comment]
It seems that way, It worked fine on 1.06 and 1.07 ( don't remember the exact version). Before installing the new version I went and Uninstaller the app and the dependency,  updated the repo and installed the newest version. Same steps were test on a firestick 4k and a nvidia shield.

**Comment by ivarbrandt** [comment]
I don't use all 10 widgets so I haven't run into this. I will look into this when I get a chance.

**Comment by ivarbrandt** [comment]
Fixed for next update.
