### ISSUE TITLE
Custom Logo Request

### ISSUE THREAD

**Issue by JBM05** [ivarbrandt/skin.fentastic#22]
I would like to replace the Kodi logo with my own image.  I was able to do this with titan and it was a very cool feature.  Is that possible or can that functionality be added?

Just downloaded the skin.  Quite good.  I'll have some ideas for you as I use it more.  Thanks for the work!

**Comment by ivarbrandt** [comment]
Are you talking about the splash image that appears right when Kodi is opened but before the home screen loads?

Or are you talking about the Kodi logo on the left panel of the home screen above the menu items?

>  I'll have some ideas for you as I use it more

Sure thing. Just please make sure to open a separate issue per request.

**Comment by JBM05** [comment]
The Kodi logo.

**Comment by ivarbrandt** [comment]
Why do you want to change it?

**Comment by JBM05** [comment]
We have a home theater and it has its own logo.  Kodi is the main thing on the screen so I would like to have the replace logo on the screen.  And besides, it is just cool feature to have if someone wants to customize the skin.

**Comment by ivarbrandt** [comment]
After some thought I've decided to not add this. Thanks for your request. I hope you continue to enjoy the skin.

**Comment by ivarbrandt** [comment]
Last time I saw Titan was back on Leia. I didn't know that it had been updated for Nexus.

**Comment by JBM05** [comment]
I don't think it has...which is why the switch on my end.

**Comment by JBM05** [comment]
I figured out how to do it manually.  Still think it would be cool, if it was in the settings.  More ideas to come
