### ISSUE TITLE
"Glitch" with In Progress Episodes widget

### ISSUE THREAD

**Issue by CaptainMoody** [ivarbrandt/skin.fentastic#24]
Since the latest update there seems to be a glitch with the heading of the In Progress Episodes widget.
In the previous version, if there were no in progress episodes the widget and the heading/title would disappear. 
Now there is no widget but the title remains, overlapping with the widget below.
I have attached a picture to clarify my terrible description :)
![image](https://github.com/ivarbrandt/skin.fentastic/assets/14757373/ed62faa8-f45a-4a9f-9642-93e214c04c00)

**Comment by ivarbrandt** [comment]
Your description of the issue was perfect. Thank you for the picture though. It always helps to be able to see the problem.

I will take a look at this. Are you using the LandscapeInfo widget display type for this widget?

**Comment by ivarbrandt** [comment]
I tested both the Landscape and LandscapeInfo widget and they both are working correctly. 

From your picture it looks like you may not be using the latest version of the skin. Please make sure that you are running v1.0.11. It is available in v1.0.1 of my repo. 

If you are running any version below 1.0.8, you'll have to delete the skin and then reinstall. I explain why here: https://www.reddit.com/r/Addons4Kodi/comments/1395yp9/fentastic_update_important/?utm_source=share&utm_medium=web2x&context=3

**Comment by CaptainMoody** [comment]
I think I was on 1.09 and hadn't noticed there was a new version of the skin, everything is working as it should again.
