### ISSUE TITLE
[Enhancement Request] Make posters size configurable

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.fentastic#25]
Hi,

congratulations on your latest big updates to FENtastic!
The stacked widgets are great, and really comfortable to use and saves extra widgets to configure.

I also followed a bit your issue with Tikipeter, that he helped you to make it possible, and I also saw you that you wanted to fit more posters in the screen, so you reduced the posters size.

Currently I'm using in my build for my users FENtastic version 1.0.7, I really like the new changes, but actually the posters size is what preventing me to update the skin.

I really like the current posters size, it's looks good on big screens: (Ignore the Hebrew)

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/88e7e680-128a-4663-9829-a9007aa8bec0)

With the reduced posters size and more in screen, it actually felt me too small for me for widget usage.
I wanted to ask if it's possible / considerable to make it configurable as a choice?
If not, I'll understand of course.

Thanks!

**Comment by ivarbrandt** [comment]
How long did you try using the newer version of the skin? I ask because I too thought that I had made the artwork sizes too small but within the first week my eyes adjusted and now I really like the end result.

**Comment by TwilightMercy** [comment]
I'll give it more time : )

**Comment by ivarbrandt** [comment]
Thank you 🙂 Keep me posted.

**Comment by TwilightMercy** [comment]
I’ll comment here again in the future :)

**Comment by TwilightMercy** [comment]
Hi friend,

First of all, new test version `1.0.12a` is blast. 
The search results window is amazing. So much more effective and UX friendly.

About the posters size, I tried to get used to it but it didn’t work out 😅

All posters look really small to me, even on big TV screen. I really like the old posters size (up to FENtastic 1.0.8, which I’m currently using in my build)

Will you consider adding an option to choose posters size in Skin settings? 
Something like “Small / Large”, or maybe the setting will configured the number of posters that fits into screen. (4 to 8 for example)

**Comment by ivarbrandt** [comment]
This isn't something that I want to do. Mainly because I like the artwork sizes I chose. But also, the only way I know how to achieve what you want to do is to have two layouts per view. The problem with this is both of the layouts will be loaded even though only one of them would be visible. This is going to contribute to memory and system resource usage as the layouts are very different from each other. If I can figure out another way to do this without having two layouts loaded per view, then I'll do my best to implement it. But if I can't, then I'm sticking with the current artwork sizes.

I recommend you show both options to your members and let them decide.

**Comment by TwilightMercy** [comment]
I understand, so there is no easy way to load only one view by configuration?

I will do a test run of course with latest FENtastic version with all the new features for my build users.

Anyway I'd be happy that if in the future you'll know how to implement it, reopen the issue and let me know : )

**Comment by ivarbrandt** [comment]
No easy way that I'm aware of. 

> I will do a test run of course with latest FENtastic version with all the new features for my build users.

Awesome. I recommend waiting for a stable release in the main repo.

**Comment by TwilightMercy** [comment]
Hi : )

Regarding the widget sizes - after the time with latest FENtastic versions and smaller widgets size, I did got used to it a bit. 
But I wanna try somehow use the original widgets sizes pre version `1.0.9a`.
From what I saw in the commits history, it was done by two commits between `1.0.9` to `1.0.9a` correct? maybe I'll try manually apply these changes back.

[Commit 1](https://github.com/ivarbrandt/skin.fentastic/commit/477c81122718bb9e9f73bb52a04270d0315ba0e2)

[Commit 2](https://github.com/ivarbrandt/skin.fentastic/commit/8350b97e5b7c6462992a32335a4f44a1c1faa7ba)

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/7895aa11-d974-4b66-814b-49effd9ef7c3)

What do you think?

-------------------------------------------------------------------------------------------------------------------------------------

Question about this:
>But also, the only way I know how to achieve what you want to do is to have two layouts per view. The problem with this is both of the layouts will be loaded even though only one of them would be visible. This is going to contribute to memory and system resource usage as the layouts are very different from each other. If I can figure out another way to do this without having two layouts loaded per view, then I'll do my best to implement it.

From my understanding of the XML code, for example for "**Poster**" display type - in `Includes_Home.xml` file it has 2 includes:
**WidgetListPoster**
**WidgetListPosterStacked**

Which they load: `InfoWallMovieLayout` variable
with its current values and sizes configuration.

Isn't is possible to load in this line:
`<include content="InfoWallMovieLayout">`

the matching view by configured skin setting? (example: small/big), and then the two possible options can be:
`<include content="InfoWallMovieLayout_small">`
`<include content="InfoWallMovieLayout_big">`

and they are configured separately and only one will load based on the chosen variable from skin settings?

It's only one display type example, so I assume it's a lot of work to do so (if possible or it will still consume system resources), so I will also understand.

**Comment by ivarbrandt** [comment]
Before you do all that, I'm going to try to implement bigger versions of each widget (Landscape, Poster, LandscapeInfo).

**Comment by TwilightMercy** [comment]
Good luck, appreciated!

can you remind me the number of widgets on screen pre version 1.0.9? (Before the resizing)
It was 5/6?

**Comment by ivarbrandt** [comment]
It was 4 posters and 3 landscape/landscapeinfo

**Comment by TwilightMercy** [comment]
Hi, Congrats on test version `1.0.15f`! Was worth the waiting, it now looks bigger and very good on TV : )

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/9b9edc31-2cff-4a6a-bc75-03c1c0d5da13)


>But also, the only way I know how to achieve what you want to do is to have two layouts per view. The problem with this is both of the layouts will be loaded even though only one of them would be visible. This is going to contribute to memory and system resource usage as the layouts are very different from each other

Asking out of curiosity, has something changed since then that made adding "Big" display types possible? or today it's a different code approach?

**Comment by ivarbrandt** [comment]
Nope. Nothing has changed. I just decided that I wasn't going to make the two different sizes optional for the main views, just the widgets. This way people can chose what look they like for the home screen.

> But also, the only way I know how to achieve what you want to do is to have two layouts per view.

This is still true. There are two different layouts but there is only one layout per view being used. This keeps the memory usage down.

I really like the way the bigger layout looks for the main views of the skin as I realized it felt pretty cramped with the smaller layout. But I still prefer the smaller layout for the widgets. So what I did was make the main views (InfoWall, WideInfoWall, Wall, and WideWall), use the bigger layout and the widgets have the option of either one.

**Comment by ivarbrandt** [comment]
You're welcome!

Also, were you asking me why I chose to add the bigger layout now and why I didn't do it when you asked me awhile ago?

**Comment by TwilightMercy** [comment]
Yes, you explained to me awhile ago here - https://github.com/ivarbrandt/skin.fentastic/issues/25#issuecomment-1590057028

And from there I didn't ask again, but other people did in this issue - https://github.com/ivarbrandt/skin.fentastic/issues/46

And it's was worth to wait for it : ) (small fact: a lot of my build users also liked the bigger widgets, I told them to just be patient)

**Comment by ivarbrandt** [comment]
Lol that is perfect timing.
