### ISSUE TITLE
[Kodi on Debian Installation Issue] ivarbrandt Repo coming up empty when trying to install the skin

### ISSUE THREAD

**Issue by oahmed5995** [ivarbrandt/skin.fentastic#26]
Currently running Kodi on Ubuntu.

I am able to add the repository  from zip with the following address without issues.
https://ivarbrandt.github.io/repository.ivarbrandt/

However, when it's time to install from the Ivarbrandt repository, I am able to access it however
the contents appear to be empty as pictured.
![Screenshot from 2023-06-11 17-10-54](https://github.com/ivarbrandt/skin.fentastic/assets/80538338/e1e6e34a-d5de-4075-a597-6a159680a976)

I did not have this issue when installing FENtastic on my firestick. Maybe something with ubuntu?

**Comment by ivarbrandt** [comment]
Which version of Kodi are you running?

**Comment by oahmed5995** [comment]
Kodi 19.4.0
Ubuntu 22.04.2

**Comment by ivarbrandt** [comment]
The skin is only for Kodi Nexus. You'll have to upgrade in order to download the skin.
