### ISSUE TITLE
[Bug] Search Results Window - No results for Hebrew language string

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.fentastic#28]
Hi,

FENtastic `1.0.12b`
Helper `0.6.12b`

Using the new search results window - searching in English works, when searching in Hebrew language - always getting no results.
In direct FEN addon - searches in Hebrew work (as always).

Screenshot for "Avengers" search in English:
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/bac42edc-32f9-43f8-8f1a-1d64820326f7)

Screenshot for "Avengers" ("הנוקמים") search in Hebrew:
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/3ef28d98-8801-4cd2-8d95-bf85d7df6fe7)

Adding debug kodi.log when searching both strings in search results window:
https://paste.kodi.tv/egokuwuceq.kodi

Thank you very much!

**Comment by ivarbrandt** [comment]
Please see the comment I made about opening issues on unreleased versions of FENtastic in your "Search String" issue.

I'll look into this. Could you send me the "avengers" search string in Hebrew so I can do some testing?

**Comment by TwilightMercy** [comment]
Sure. 

The string is:
הנוקמים

**Comment by ivarbrandt** [comment]
Did you make sure that the language in Kodi is set to Hebrew and so the metadata language in Fen?

**Comment by TwilightMercy** [comment]
Yes, both configured on Hebrew

**Comment by ivarbrandt** [comment]
Ok I need you to try something for me. Go to the movies main menu in Skin settings and click "Rename", type in something in Hebrew and then return to the home screen. Does it show the main menu label now in Hebrew or is it empty?

**Comment by TwilightMercy** [comment]
Renamed both movies and shows menus items names to Hebrew successfuly. 

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/1571258a-101e-478a-90a2-9da29f33c673)

**Comment by TwilightMercy** [comment]
You are correct.
Based on debug log I've created now - comparing the two searches, you can see:


**FENtastic Search Results Window search for "הנוקמים" ("Avengers" in Hebrew)**

```
Line 604: 2023-06-14 18:15:18.158 T:12036   debug <general>: CDirectoryProvider[plugin://plugin.video.fen/?mode=build_movie_list&action=tmdb_movies_search&query=הנוקמים]: refreshing..
Line 605: 2023-06-14 18:15:18.158 T:12036   debug <general>: CDirectoryProvider[plugin://plugin.video.fen/?mode=build_tvshow_list&action=tmdb_tv_search&query=הנוקמים]: refreshing..
Line 614: 2023-06-14 18:15:18.436 T:4820    debug <general>: CScriptRunner: running add-on script Fen('plugin://plugin.video.fen/', '7', '?mode=build_movie_list&action=tmdb_movies_search&query=הנוקמים')
Line 649: 2023-06-14 18:15:19.148 T:2380    debug <general>: CScriptRunner: running add-on script Fen('plugin://plugin.video.fen/', '8', '?mode=build_tvshow_list&action=tmdb_tv_search&query=הנוקמים')
```


**FEN Search --> Movies search for "הנוקמים" ("Avengers" in Hebrew):**


```
Line 577: 2023-06-14 18:18:48.338 T:7012    debug <general>: CGUIMediaWindow::GetDirectory (plugin://plugin.video.fen/?mode=build_movie_list&action=tmdb_movies_search&query=%D7%94%D7%A0%D7%95%D7%A7%D7%9E%D7%99%D7%9D)
Line 580: 2023-06-14 18:18:48.340 T:5936    debug <general>: CScriptRunner: running add-on script Fen('plugin://plugin.video.fen/', '10', '?mode=build_movie_list&action=tmdb_movies_search&query=%D7%94%D7%A0%D7%95%D7%A7%D7%9E%D7%99%D7%9D')
Line 617: 2023-06-14 18:18:51.271 T:8012    debug <general>: CPythonInvoker(23):  ?mode=build_movie_list&action=tmdb_movies_search&query=%D7%94%D7%A0%D7%95%D7%A7%D7%9E%D7%99%D7%9D
Line 659: 2023-06-14 18:19:06.024 T:7012    debug <general>: Saving fileitems [plugin://plugin.video.fen/?mode=build_movie_list&action=tmdb_movies_search&query=%D7%94%D7%A0%D7%95%D7%A7%D7%9E%D7%99%D7%9D]
```

The URL-encoded string:
**%D7%94%D7%A0%D7%95%D7%A7%D7%9E%D7%99%D7%9D**

After URL-decode in UTF 8 character set is indeed the Hebrew string for "Avengers" in Hebrew:
הנוקמים

**Comment by ivarbrandt** [comment]
Yeah that makes sense. I have fixed this for the next test version. I only tested it with the Hebrew string that you gave me for "Avengers". I also only tested it with English set as my language for Kodi and metadata in Fen. So test it out and lemme know if it is working correctly. The changes will be in the `1.0.12d` update.

<img width="1176" alt="Screen Shot 2023-06-15 at 5 54 23 AM" src="https://github.com/ivarbrandt/skin.fentastic/assets/54084201/e7bef3a1-0822-426a-a1bb-1f0339e53152">

**Comment by TwilightMercy** [comment]
Thank you very much, once 1.0.12d will be releases I will test it on various Hebrew string.

By the way, what was the solution? UTF-8 URL encoding every non-English string?

**Comment by TwilightMercy** [comment]
Thank you for the explanation

**Comment by ivarbrandt** [comment]
You're welcome. `1.0.12d` is up.

**Comment by TwilightMercy** [comment]
Version `1.0.12d`
Kodi Language - Hebrew
FEN Metadata - Hebrew 

Hebrew searches are working 💪🏻

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/96788f60-7fef-4206-9b4c-0b9b33cd7bb7)
