### ISSUE TITLE
Option to order main screen - Feature Request

### ISSUE THREAD

**Issue by 1advent** [ivarbrandt/skin.FENtastic#3]
I don't know if it is an issue perse, but I would love the ability to organize TV Shows to the top instead of Movies. 

And i would like to point out that this is a very minor feature request, this skin is great and I really love it. So far as my opinion goes, feel free to close it if it is too much work or isn't the direction you want to go. I really appreciate it the way it is. 

Thanks for a great skin, it is my new go to.

**Comment by SoulReaverFan** [comment]
I second this. Would be nice to be able to customize the order of the main menu items in general. Nice work on this skin 👍

**Comment by ivarbrandt** [comment]
This isn't something I currently plan on adding. 

Thanks for the request and I'm happy you're enjoying the skin.
