### ISSUE TITLE
[Error] Error when fresh installing FENtastic

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.fentastic#31]
Hi,

I've noticed that when installing FENtastic (using latest test version `1.0.12d`)

After installation - an error pop ups in Kodi, and then everything else is working as usual - no issues with configuring widgets, etc.. but letting you know.

Screenshot:
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/d35ff339-a057-4884-9857-b82e97c27ff8)

Adding kodi.log in debug mode of fresh install of FENtastic `1.0.12d` on clean and empty Kodi:
https://paste.kodi.tv/kebeyujevu.kodi

the specific error from the log is:
```
2023-06-16 13:08:49.651 T:1808    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnboundLocalError'>
                                                   Error Contents: local variable 'SPaths' referenced before assignment
                                                   Traceback (most recent call last):
                                                     File "C:\Users\twilight\AppData\Roaming\Kodi\addons\script.fentastic.helper\resources\lib\default.py", line 3, in <module>
                                                       routing()
                                                     File "C:\Users\twilight\AppData\Roaming\Kodi\addons\script.fentastic.helper\resources\lib\modules\router.py", line 60, in routing
                                                       return SPaths().re_search()
                                                   UnboundLocalError: local variable 'SPaths' referenced before assignment
                                                   -->End of Python script error report<--
```

**Comment by TwilightMercy** [comment]
Closing by issue rules for test version

**Comment by ivarbrandt** [comment]
Thanks for pointing this out. I haven't gotten that error nor been able to reproduce it.

I did make a change though so hopefully it'll be fixed for `1.0.12e`

**Comment by TwilightMercy** [comment]
Hi,

I noticed that you updated FENtastic test version to `1.0.12e`

I can confirm the issue has fixed and no error on fresh install 👍🏻

**Comment by ivarbrandt** [comment]
Glad to hear it 😄
