### ISSUE TITLE
Request to Bring Back "Shift" View Type in FENtastic 1.012e Test Version

### ISSUE THREAD

**Issue by DevGeniusCode** [ivarbrandt/skin.fentastic#32]
Hi,

I’m using FENtastic 1.012e test version, and I've noticed that the "Shift" view type has been removed compared to older FENtastic versions.

**Request:**
Can it be brought back, please? I'm using it in my Kodi setup.

Thank you.

**Comment by ivarbrandt** [comment]
I'll think about it. That view caused me so many headaches.

**Comment by DevGeniusCode** [comment]
Thank you!
