### ISSUE TITLE
Request to Add Trakt List Search Option in FENtastic 1.012e Test Version

### ISSUE THREAD

**Issue by DevGeniusCode** [ivarbrandt/skin.fentastic#33]
Hi,

I'm using FENtastic 1.012e test version, and I really like the new search results window. However, I would like to suggest an enhancement to the add-on.

**Request:**
Could you please consider adding an option in the skin settings to enable searching for Trakt lists as well? Currently, I found the following search path (in kodi.log on debug mode) while searching for Trakt lists in FEN:
plugin://plugin.video.fen/?mode=trakt.list.search_trakt_lists&query=

Thank you.

**Comment by ivarbrandt** [comment]
I don't have a widget that can display lists so I won't add it as a widget. What I can do is add a button next to the search icon in the Search Results Window that opens a keyboard and let's you search Trakt lists directly. It will pass the query to Fen and the window that will open with the results will be in Fen.

**Comment by DevGeniusCode** [comment]
Thanks for the feedback, maybe I'm getting confused, but I see that I can add lists as a widget to the main screen, attached a picture. I set it as LandscapeInfo, and you can also do it as a poster (but I won't show the name and details of the list).
![image](https://github.com/ivarbrandt/skin.fentastic/assets/136935333/ac98154c-c380-4ea6-90b4-b6e61de3ec88)

**Comment by ivarbrandt** [comment]
That's my point. The widgets I have weren't really designed to handle lists. That's why I think it is better to have a shortcut for searching trakt lists. So that when the window opens you'll be able see more items at one time.

**Comment by DevGeniusCode** [comment]
I believe this a fair compromise. Since already creating a separate window for the lists, I suggest displaying them as posters.
These posters would only show the name of each list, without displaying additional details (LandscapeInfo). In a side window (InfoPanel), we can present the complete details of the selected list, including its name, number of items, author, and other relevant information.

[The home screen does not have this information.]

**Comment by ivarbrandt** [comment]
The window will be a list window from Fen. There's nothing I can do about controlling that view type. Also, Posters aren't designed to display list information. They are designed to display content.

**Comment by ivarbrandt** [comment]
I have added a new widget type for Trakt lists. They will be displayed the same way the other search widgets are displayed.

I have also added a Trakt button that when clicked, pops up a keyboard to search Trakt lists. 
Try out both and let me know which one you prefer.

The changes will be available in `1.0.12f`.

**Comment by DevGeniusCode** [comment]
Thank you very much for adding the widget for Trakt Lsits.
I noticed that there is an error [1] in the widget you created, but there is no error in the other forms of the original widgets (WidgetListPoster for example).
I suggest using the fourth widget you recently added, WidgetListCategoryStacked, I tried to use it, but there is an error [2] when loading the sublist.
On the home the widget is running, and the error occurs on the search results window.

Keep up the good work :)

Pictures are attached for illustration.
home:
![image](https://github.com/ivarbrandt/skin.fentastic/assets/136935333/b938a787-719f-4585-8c91-0d939135c44b)

 search results window:
![image](https://github.com/ivarbrandt/skin.fentastic/assets/136935333/9b81027a-ca02-4b2e-be26-8218d363fb46)

Error 1:
`2023-06-19 00:49:00.895 T:18316    info <general>: Loading skin file: Custom_1121_SearchResults.xml, load type: KEEP_IN_MEMORY
2023-06-19 00:49:01.698 T:10360   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.fen/?mode=build_movie_list&action=tmdb_movies_search&query=
2023-06-19 00:49:01.761 T:1136    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.fen/?mode=build_tvshow_list&action=tmdb_tv_search&query=
2023-06-19 00:49:01.795 T:10024   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.fen/?mode=build_movie_list&action=tmdb_movies_search_sets&query=
2023-06-19 00:49:01.938 T:17196    info <general>: ###Trakt Error###: 400 Client Error: Bad Request for url: https://api.trakt.tv/search?type=list&fields=name%2C+description&query=&limit=50&page=1
2023-06-19 00:49:01.939 T:17196   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: cannot unpack non-iterable NoneType object
                                                   Traceback (most recent call last):
                                                     File "C:\Users\my_user_name\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\fen.py", line 5, in <module>
                                                       routing(sys)
                                                     File "C:\Users\my_user_name\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\router.py", line 57, in routing
                                                       return exec('trakt_lists.%s(params)' % mode.split('.')[2])
                                                     File "<string>", line 1, in <module>
                                                     File "C:\Users\my_user_name\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\indexers\trakt_lists.py", line 59, in search_trakt_lists
                                                       lists, pages = trakt_search_lists(search_title, page)
                                                   TypeError: cannot unpack non-iterable NoneType object
                                                   -->End of Python script error report<--`


Error 2:

`2023-06-19 11:22:46.726 T:14468   error <general>: EXCEPTION: Non-Existent Control 270171
2023-06-19 11:22:46.731 T:14468   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'RuntimeError'>
                                                   Error Contents: Non-Existent Control 270171
                                                   Traceback (most recent call last):
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.fentastic.helper\resources\lib\default.py", line 3, in <module>
                                                       routing()
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.fentastic.helper\resources\lib\modules\router.py", line 15, in routing
                                                       return widget_monitor(params.get("list_id"))
                                                     File "C:\Users\User\AppData\Roaming\Kodi\addons\script.fentastic.helper\resources\lib\modules\widget_utils.py", line 19, in widget_monitor
                                                       stack_control = window.getControl(int(stack_id))
                                                   RuntimeError: Non-Existent Control 270171
                                                   -->End of Python script error report<--`

**Comment by ivarbrandt** [comment]
I mean I'm no longer accepting feature requests for any test version that is `1.0.12x`.

That error pops up every time the search window is opened, whether or not you search anything. This is because it is not passing the TRAKT search path a query until later when you type it in. As far as I know, this error is related to Fen and not my skin.

**Comment by DevGeniusCode** [comment]
I understand, so I'd love to choose the option with the widget, instead of the button above.
Thank you for your support :)

**Comment by ivarbrandt** [comment]
Ok widget it is. I'll change the function of the Trakt button to link directly to the main Trakt lists menu in Fen.

I'm also going to try to see if I can at least make it so that error doesn't pop up when you open the search window. This is the final thing that will be done for the release version `1.0.13`.

> Thank you for your support :)

You're welcome. It's really cool to see you take an interest in my skin. I hope you're able to modify and change it to suit your specific needs and wants.

**Comment by TwilightMercy** [comment]
One of my build users that really loves FENtastic after the build has transitioned from simple favourites menu to widgets : )

Note:
>Ok widget it is. I'll change the function of the Trakt button to link directly to the main Trakt lists menu in Fen.

Will it cause any errors from FEN opening the mani Trakt lists if no Trakt account is connected? because most of the users not always uses Trakt and connecting it to FEN.

**Comment by TwilightMercy** [comment]
> > One of my build users that really loves FENtastic after the build has transitioned from simple favourites menu to widgets : )
> 
> That's so cool. Widgets is where it's at 😃
> 
> > Will it cause any errors from FEN opening the mani Trakt lists if no Trakt account is connected?
> 
> I'm not sure. But they can disable Trakt search results from the Search window in Skin Settings. This will make it so that non-Trakt users don't experience any errors.

Yes, about the Trakt search results I agree.
I mean about the separate Trakt button above - if it will pop up an error if Trakt account is not connected

**Comment by ivarbrandt** [comment]
@DevGeniusCode 

I have added a workaround to silence the errors when having Trakt lists enabled in the Search Results window. Test it and let me know.

**Comment by TwilightMercy** [comment]
I also tested :)

On fresh install and first ever open of the search results window - the error pop ups once or twice, but then it stops and never pops up again. That’s acceptable imo.

**Comment by ivarbrandt** [comment]
> On fresh install and first ever open of the search results window - the error pop ups once or twice, but then it stops and never pops up again. That’s acceptable imo.

Good catch. I added a fix for this in the next test version.

**Comment by TwilightMercy** [comment]
You’re the best.

**Comment by TwilightMercy** [comment]
> > The build and group has growed and developed so much since FENtastic
> 
> That's great! How many members did you start out with?

Well.. 0 (Aug 2022)

**Comment by ivarbrandt** [comment]
You've more than doubled in less than a year! That's awesome. Congrats!

@TwilightMercy 
@DevGeniusCode 

Alright, all fixes have been pushed. Nothing more till `1.0.13` is up. 
Thank you both for the feature suggestions and helping me test and report bugs.

**Comment by TwilightMercy** [comment]
> Alright, all fixes have been pushed. Nothing more till `1.0.13` is up. Thank you both for the feature suggestions and helping me test and report bugs.

Amazing release! I'm going soon to start working on preparing FENtastic `1.0.13` version to be updated in my build (from `1.0.7`).


> Sweeet thanks! I noticed those errors and I was able to mitigate them by setting the Trakt search path query to "none" instead of an empty string. I did this by creating a new string specifically for the Trakt queries called SearchInputTraktEncoded.

Question regarding this (from https://github.com/Tikipeter/repository.tikipeter/issues/217#issuecomment-1597727188) - 
From next FEN update Tiki will allow using Trakt lists freely without having to be authorized to Trakt account. Is a change of your workaround in FENtastic needed? or will work the same?

**Comment by ivarbrandt** [comment]
I will updated the code in the Helper when these changes are made in Fen. It will work the same way when it's all said and done.

**Comment by TwilightMercy** [comment]
`FENtastic` 1.01.3
`FEN` 3.1.17

No errors at all with Trakt lists from FEN / FENtastic search results window - with/without Trakt account connected 👍🏻

**Comment by DevGeniusCode** [comment]
I checked now with mine, and indeed there are no errors either. Thank you very much for your good work!
