### ISSUE TITLE
[Potential Bug] Search Results Window - Hidden Widgets

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.fentastic#34]
Hi,

FENtastic `1.0.12e`

I'm not sure how much it really affects the performance/experience, but letting you know what I've encountered:

1. Opening the search results window for the first time
2. Searching "avengers"
3. Getting widgets results
4. Pressing back
5. Opening the search results window again
6. "avengers" is in "Recent searches" list, I didn't click on it or on new search
7. I go right with the keypad (or later hovering with the mouse) and the background + InfoPanel changes according to the widgets from "avengers" search, like it's still loaded in the background but partially hidden.

Video:
https://streamable.com/9gh3pl

**Comment by TwilightMercy** [comment]
Closing by issue rules for test version

**Comment by ivarbrandt** [comment]
Whoops. I noticed that earlier today too. I was like what is happening haha. 

It is fixed for the next test version.

**Comment by TwilightMercy** [comment]
No problem 👍🏻

And about the widgets bug, so it did load theast search results again?

**Comment by ivarbrandt** [comment]
Well, it didn't clear the search query. Which makes sense because I didn't need to do that when it was just the keyboard option. But since I implemented both, each have different logic but some of it overlaps.
