### ISSUE TITLE
[Enhancement] Separate Watched Items Toggle for Search Results Window

### ISSUE THREAD

**Issue by DevGeniusCode** [ivarbrandt/skin.fentastic#36]
In the previous search form, users had the convenient ability to show or hide watched items by simply opening the side window (Media Menu) and clicking on Watched Toggle. However, with the introduction of the new form, the side window has been removed, and the option to manage watched items is now controlled by the FEN settings (because now it's widgets).

Currently, the FEN settings (Settings > Navigation > Widgets) govern the visibility of watched items in both the search screen and the home screen. This means that if users choose to enable the hiding of watched items on the home screen, they have no option to disable it on the search screen without going to settings each time. As a user, I personally prefer to hide watched items on the home screen since there is no need to see offers of items that have already been watched.

**Request**:
Add to the new search window an option to show/hide viewed items, without affecting the home screen.
Alternatively, by default the search results window will always display items that have already been watched .

**Code Snippet:**
`userdata\addon_data\plugin.video.fen\settings.xml`
`<setting id="widget_hide_watched">false</setting>`
This is the section of code in the settings file that manages the display settings of widgets.

**Comment by Tikipeter** [comment]
This is outside the scope of a skin. Even if a side blade was added to the skin with a Hide Watched toggle, it would make no difference as to what listitems were displayed. This needs to be addressed in Fen code.

**Comment by ivarbrandt** [comment]
> Even if a side blade was added to the skin with a Hide Watched toggle, it would make no difference as to what listitems were displayed.

This is exactly what I was about to try. Good looking out. Thank you.

**Comment by DevGeniusCode** [comment]
> This is outside the scope of a skin. This needs to be addressed in Fen code.

Ok, thanks for your feedback, I opened an issue in your skin :)
