### ISSUE TITLE
[Bug] Blank Search Results Window when spath_cache.db file doesn't exist

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.fentastic#38]
Hi,

First of all, sorry for all the mess during last 2 days around Tikipeter's GitHub, and for making you concerned about FENtastic, regarding the issue with my build. As Tikipeter said, everything is fine in your end and we'll fix the mess : )

-----------------------------------------------------------------------------------------------------------------------------------------

FENtastic `1.0.13`
I've found out small bug when first ever fresh installing the skin, the current `script.fentastic.helper` userdata directory contains:

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/d5573d26-a549-44ce-9fd7-21758795d6d3)

Then, opening Search Results Window - getting the following empty window:
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/6ad0d36a-746d-40af-a84a-e9c4c83b9e6e)

Then when pressing back again, the file `userdata\addon_data\script.fentastic.helper\spath_cache.db` is created (empty), and then - opening again the search results window shows the correct "Your search history is empty" window:

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/7d377839-d18a-4daf-ae09-047f3309c5a1)

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/8f78f30c-0e84-47c9-93b9-40aa62df985b)

I've recreated this issue on another device itself, with fresh and first install of FENtastic `1.0.13`, then opening the search results window.

Thank you very much for all the work.

**Comment by ivarbrandt** [comment]
> First of all, sorry for all the mess during last 2 days around Tikipeter's GitHub, and for making you concerned about FENtastic, regarding the issue with my build. 

All good. Thanks for reaching out. I'm glad you're figuring it out :)

As for that bug, I'll look into it when I get a chance.

**Comment by ivarbrandt** [comment]
I added a fix for next update. Let me know if it works.

**Comment by TwilightMercy** [comment]
Thank you I will. can you notify me here when it gets released?

**Comment by ivarbrandt** [comment]
Sure. It'll be in the test version `1.0.13a`

**Comment by ivarbrandt** [comment]
`1.0.13a` is up on the test repo

**Comment by TwilightMercy** [comment]
Updated to FENtastic` 1.0.13a` + Helper `0.6.13a`

Unfortunately, same exact behavior on fresh install. maybe it's possible to create, if not exists, empty spath_cache.db file on Kodi startup? (before the search results window will be opened for the first time)

**Comment by ivarbrandt** [comment]
Strange. 

> before the search results window will be opened for the first time)

It shouldn't matter because the `spath_cache.db` file should be created on the opening of the search window. What you're saying is that isn't the case on fresh installs so reloading the window creates it.

I'll see if initializing it on the loading of the home screen fixes it. Changes will be in `1.0.13b`.

**Comment by TwilightMercy** [comment]
I've tested fresh install on 1.0.13b.

That's so strange. I confirmed and saw that after the fresh install (before opening the search results window), `spath_cache.db` file got created in helper userdata directory.

But still got the same behavior - open search results window, empty window, go back, open search results window - and it works.

**Comment by ivarbrandt** [comment]
Noooo. Ok, I'll have another look at it later.

**Comment by ivarbrandt** [comment]
I've hopefully added a fix in `1.0.13c`. Try it out and let me know.

**Comment by TwilightMercy** [comment]
Fixed successfully 👍🏻

Thank you very much.

**Comment by ivarbrandt** [comment]
I'm glad that fixed it. At least I know what is going on now. 

I don't really like that fix though so I'll be trying something else.

**Comment by TwilightMercy** [comment]
Sure, let me know if need some testing

**Comment by ivarbrandt** [comment]
I couldn't find a different way to fix it so I'll just leave the fix as is.
