### ISSUE TITLE
[Question] Stacked Widgets Performance 

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.fentastic#39]
Hi,

Question about Category Stacked Widgets in terms of performance.

For example , configuring a category stacked widgets of FEN --> Movies menu:
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/fab8b15a-601e-4120-9af5-7399e62b8c5f)

When starting Kodi and the widgets load, do all the widgets for ALL categories lists are loading at the same time?

From my testing - yes, because when loading is finished I go immediately to the last widget category - and all of its Posters (display type) widgets show up **immediately** , and not only when standing on the current category.

I'm asking that in terms of performance, because on PC everything loads very fast and almost instantaneous.
But for Android TV devices with lower specs, the initial load takes more time.

 and If the case I described is correct - could it be changed to only load the current category widget you "stand" on? (only relevant for stacked category widgets - rest of the widgets should load anyway at startup). To reduce initial loading time

Thank you

**Comment by ivarbrandt** [comment]
Yes, they all load on startup. No, I don't want to change this behavior.

**Comment by TwilightMercy** [comment]
All good 👍🏻

May I ask only for the reason? 
or if it can be optional? (to choose to load all category widgets at startup / only the first category widget and startup, and then loads as you stand on another category)
