### ISSUE TITLE
[Enhancement Request] Bring back "Uninstall" button in DialogAddonInfo.xml

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.fentastic#40]
Hi,

First of all, I really liked your new design approach ("UI overhaul") in latest `FENtastic` test updates. Makes Kodi more clean and fresh.

I noticed a difference between `1.0.13` and latest `1.0.13f` (test version) I've installed. that "Uninstall" button in addon dialog was removed?

**Screenshot from `1.0.13`:**
![IMG000](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/a1401632-de71-49cf-b1e6-bf5818d49eb3)

**Screenshot from `1.0.13f`:**
![image_2023-06-30_23-33-53](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/ed7bf6bb-5b62-45b9-a314-db99723f15bd)

If it was intentional, would you consider bringing it back? well.. it's mandatory 😅

Thanks and keep up the great updates.

**Comment by ivarbrandt** [comment]
It wasn't removed. Try scrolling to the right in that button list.

**Comment by TwilightMercy** [comment]
You're right, my bad lol.. I'm using to seeing it immediately so I didn't try to scroll

**Comment by ivarbrandt** [comment]
Lol I get it. I might resize the buttons so they all fit on the screen like they did before.

**Comment by TwilightMercy** [comment]
Great, thank you.

**Comment by ivarbrandt** [comment]
Resized all the buttons for the next test version.

**Comment by TwilightMercy** [comment]
Great, thank you!

**Comment by TwilightMercy** [comment]
Awesome 👍🏻

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/4da993a3-a2f2-4e4f-befd-b487cf813b3b)
