### ISSUE TITLE
[Issue] Search Dialog background transparency

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.fentastic#41]
Hi,

Playing with the great and refreshing design of FENtastic `1.0.13f`, I noticed:

By default I'm using of course the new Search Results Window and it's great, but I turned it off to search something from the original Search Dialog, and it looks like it has no solid/slight background for each line the in the dialog, and it overlaps with the background which can affect reading the text.

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/5634a289-c480-462d-85de-d7dab464d996)

Letting you know : )

**Comment by ivarbrandt** [comment]
Yeah that doesn't look right lol. I'm not done yet with the all the changes to the UI. 

I appreciate you letting me know though.

**Comment by TwilightMercy** [comment]
Looking good 👍🏻 (ignore Hebrew)

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/97915e51-c47e-4840-817f-9f564677d1fd)

**Comment by TwilightMercy** [comment]
I’ve noticed that you reduced the search dialog’s height, and it is now scrollable. 

Can you add side scrollbar so it will be more understandable to scroll?

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/96492829-30db-4c81-bf00-b15f248dde4a)

**Comment by ivarbrandt** [comment]
> Can you add side scrollbar so it will be more understandable to scroll?

What do you mean?

**Comment by TwilightMercy** [comment]
pre-overhaul - the whole search dialog dialog items were shown.

Now, you only see first half of the items:
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/4a6e61be-a9bc-4b83-b66b-da09f5f91769)


And if you scroll down you see the rest:
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/835e9beb-638b-41d5-915f-0701684b5dd0)


There is no scrollbar, so at first I didn’t know I need to scroll down 😅

**Comment by ivarbrandt** [comment]
I don't like a scroll bar for that small dialog. I've implemented some arrows on the top and bottom of the window. Let me know what you think. 

Also, I need your help. After you update to the latest version could you please let me know if the 'Disable search results window' in Options in Skin settings is toggled on or off by default (fresh skin install).

I would also like to know that when it's toggled to off, are the categories that drop down all toggled to on by default?

Thanks!

**Comment by TwilightMercy** [comment]
Thanks, the arrows are looking+working good. 


Default Skin settings on fresh skin install:
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/f7f2af56-3119-4cb0-9016-e0b8968d8e47)

When disabling search results window:
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/0139e643-f873-4b68-b5f8-1d078643b667)

I suggest by default on fresh install having the settings like that:
For movies+shows will work immediately when searching, without manually enabling them. And the rest - manually  by user preference   
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/f2dabb9b-2fdb-4580-97d0-a9d9345ac988)

**Comment by ivarbrandt** [comment]
Thanks for trying that out for me. I'm going to have all the categories default to on.

**Comment by TwilightMercy** [comment]
You're welcome.

**Comment by TwilightMercy** [comment]
Hi, question regarding the dialog size for context menu. the arrows you've added to those dialogs (example: search dialog, context menu, etc) are good.

But specific only for the context menu:
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/ad769d5f-a66f-442d-99f0-ebbe2432aa86)

I liked the old length of the window: (Screenshot from pre-overhaul version)
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/5d4bdf75-cc33-4db8-8a27-44f4637b9b48)

Specific for context menu, will you consider expanding it's length? and if's not (totally fine), can you instruct me in skin's XML files how to? (to apply it manually in my version)

**Comment by ivarbrandt** [comment]
I thought about how I wanted to implement changes to the context menu for a long time. I also tried many different approaches so the one you see is the one I decided on.

If you want to change it back you can go find the changes in my previous commits. The window is called DialogContextMenu.xml. Or you could install 1.0.13c from the test repo. That version was before all of the UI changes were implemented.

**Comment by TwilightMercy** [comment]
Thank you,

I switched `DialogContextMenu.xml` to the file from version `1.0.13c`, and it worked, but indeed without the new UI design:
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/6bda386e-1bfa-49dd-9041-5f1d78763f7a)


I assume using the latest `DialogContextMenu.xml` with the new design, but keeping the original menu height will require specific changes

**Comment by ivarbrandt** [comment]
Yes it will. The original menu height was dynamic according to how many items there were in the context menu. 

The combination of things you're looking for is in one of the recent commits I just don't know which one.

**Comment by TwilightMercy** [comment]
No problem, I'm fine with the using old context menu specifically. Thank you very much!
