### ISSUE TITLE
Highlighting focused item in widget lists.

### ISSUE THREAD

**Issue by Tikipeter** [ivarbrandt/skin.fentastic#42]
If you're still interested in having a highlight for the focused widget item, then I have a way that worked for me when I recently changed Fenstruary widgets to fixedlists.

I passed the includes a new `list_id` param, and then used
```
<visible>$PARAM[focused] + Control.HasFocus($PARAM[list_id])</visible>
```
in the include.

Then the highlight only shows when the list is focused. Since the includes are used for other windows as well, you'd likely have to fiddle with things. But that's the way to get the highlight on the focused item to only show when the list is focused.

**Comment by ivarbrandt** [comment]
THANK YOU!!! I can't even describe to you how grateful I am that you let me know about this. I have been trying to figure this out for quite awhile now. I tried the above solution before but I forgot to pass in the `list_id` param. Again, thank you so much.

Btw, have you tried the latest version of FENtastic? I overhauled many UI elements. When you get a chance to try it, can you let me know if you experience the same performance as before or if it is slower? I did my best to keep the new texture sizes relatively small in order to impact performance as little as possible.

**Comment by Tikipeter** [comment]
I love all the changes.

To be honest, it's getting to a point where I might have to start using your skin, as I don't have the patience to bring in all the rounded edges etc into Fenstruary and I really like them.

So you've given me a bit of a dilemma really. :) Because I will still enjoy fiddling with my skin a little bit when the mood takes me.

**Comment by ivarbrandt** [comment]
> I love all the changes.

Sweet! Me too. It's feels like the skin is now in the 21st century lol.

> it's getting to a point where I might have to start using your skin, as I don't have the patience to bring in all the rounded edges etc into Fenstruary and I really like them.

I feel you. Implementing all the rounded textures took quite some time. 

Well when you're ready, come on over to the FENtastic side of life. I'd love to have you :)

**Comment by ivarbrandt** [comment]
I set up all of the widgets by passing in the `list_id` and it looks sooo clean. Thanks again.

I ran into a bit of an issue when updating all of the controls that I haven't been able to solve. The `ProgressBar` include that I use to display progress for items, only shows when items are unfocused. Then, they are hidden when the item is focused. 

So I'm not sure how to pass in a `list_id` to an unfocused item or whether or not that would even work. I tried to pass in the `list_id` to my `ProgressBar` include but it wouldn't work. I'm not sure if this is something that can be done. What do you think? Is there a better way to go about this? I marked where one of the `ProgressBar` includes is used in the skin. You can search this to find it:

`<!-- TODO Fix progress bar for WidgetListLandscape -->`

I also tried to set an `id` to a control that I know is only visible when focused and then use `!Control.IsVisible(id)` for the visibility condition of the progress bar and it ended up crashing my Kodi multiple times lol.

**Comment by Tikipeter** [comment]
I didn't have much luck with it to be honest. Code that should have worked didn't work.....

**Comment by ivarbrandt** [comment]
Aww man. Thanks for giving it a shot.

>  Code that should have worked didn't work.....

Same here. I know the progress bar is different but I'm surprised nothing has worked. 

Anyways, I have an idea for how to achieve a similar effect. I'll let you know if it works.

**Comment by ivarbrandt** [comment]
The fix worked! Had to tweak it a little bit but I think it looks good. Changes are in `1.0.13m`.

**Comment by TwilightMercy** [comment]
> The fix worked! Had to tweak it a little bit but I think it looks good. Changes are in `1.0.13m`.

I'm glad it worked and the blue frame is back! it's been a long time. I tested `1.0.13m` and all blue frames looks great and clean.

One thing I noticed it's still missing for `Poster` view type, screenshot:

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/671ee5cf-a371-4aa9-95f7-8348982b17dd)


Can it be added as well?

**Comment by ivarbrandt** [comment]
I like the way that view looks without the frame. I think it looks a lot cleaner. The alignment was definitely off though so I fixed that. 

Next time, please open a separate issue as your request isn't relevant to the issue of the highlighting of focused widget items.
