### ISSUE TITLE
[Feature] Lock 🔒 Media View option

### ISSUE THREAD

**Issue by Nuklear92** [ivarbrandt/skin.fentastic#44]
Is there a possibility to have an option to lock your media view of choice. 

For example, when I want to see lists of Movies or TV-Shows as of 1.0.14 it always default/reset back to "Wall" media view after manually choosing "List" view. 🤔

**Comment by ivarbrandt** [comment]
The view type is something you set up in Fen. As of Fen `v3.1.18`, you'll need to re-set your views in Fen settings.

**Comment by Nuklear92** [comment]
Thanks, I got it! 👍
