### ISSUE TITLE
[Issue] Trakt search always appears in Search Results Window (1.0.14)

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.fentastic#45]
Hi,

Congrats on officially releasing version `1.0.14` after extensive and amazing UI overhaul!

I saw in changelog that you changed Trakt widget type in search results window to stacked category widget + Poster display type. great change and very comfortable to use and navigate between trakt lists items.

Only thing I noticed that using `HideTraktResults` as a condition to show the trakt search is missing, therefore trakt search results always show up even when it's disabled in skin settings.

I added the condition back for the two new includes in `Custom_1121_SearchResults.xml` and works as excepted: 

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/5660186f-e26b-4722-b338-7fd68c249583)

(Ignore the `plugin.video.twilight` code changes, it's in my fork after I pulled `1.0.14` changed from main repo)

Keep the great updates!

**Comment by ivarbrandt** [comment]
> Congrats on officially releasing version 1.0.14 after extensive and amazing UI overhaul!

Thank you!

Haha oops. I forgot to put that back in. Thanks for letting me know.
