### ISSUE TITLE
Feature Request: Additional widget display types 

### ISSUE THREAD

**Issue by IG2022** [ivarbrandt/skin.fentastic#46]
Hey there. Great work with the new update of Fentastic! it looks incredible and is running really fast I'm really enjoying using the skin. 

I have a feature request that I'm hoping you'll entertain but if it is too difficult or not something you are up to  I understand. 

For the widget display types at the moment there are  3 options, in regard to the size of each type they work very well on a smaller screen like for a laptop or tablet, however on a bigger screen like a larger tv they look a little small. I was hoping that you could add some additional display types that are a little larger, for example big landscape and big poster and big landscape info that might accomodate larger screens.

Thanks again for all the work you put into the skin I know we all appreciate it.

**Comment by Nuklear92** [comment]
I second this! I also have noticed this as well, where the Landscape media view for the homescreen widgets is fairly small, same for posters, etc. It would be awesome if they were a bit bigger so each poster, or landscape are more in your face noticeable instead of too small and you can barely make up for the artwork, colors, etc. 😃 other than that the new update looks clean, simple and enjoyable. 👍

**Comment by ivarbrandt** [comment]
Ya'll just blind lol. 

So instead of 6 posters, 5? And as for the landscape and landscapeinfo widgets, the only other size I can go down to is 3 per row. And those were huge in default Estuary.

**Comment by IG2022** [comment]
> Ya'll just blind lol.
> 
> So instead of 6 posters, 5? And as for the landscape and landscapeinfo widgets, the only other size I can go down to is 3 per row. And those were huge in default Estuary.
> 
> Also, 3 landscapeinfo or landscape items per row doesn't look good with 5 posters per row. I know cause I've tried.

Sure 5 for the posters would would work perfectly if that would increase the size a little bit and as for the landscape and landscape info if you could bring it down to that 3 that would be absolutely fine as well. Whatever you could do to increase the size even if it's just slightly would be greatly appreciated! Again if you feel that if would compromise the look of the over all skin then it's not a big deal but I just thought I'd ask!

**Comment by ivarbrandt** [comment]
I appreciate both of your inputs and perspectives. I'm going to try to make bigger widget sizes for Poster, Landscape, and LandscapeInfo.

**Comment by IG2022** [comment]
> I appreciate both of your inputs and perspectives. I'm going to try to make bigger widget sizes for Poster, Landscape, and LandscapeInfo.

Thanks for considering this, I really appreciate it!

**Comment by ob89** [comment]
It is really small on a 4k television. It used to be really big and comfortable. I would like to ask for it too. Before the update it was really big and comfortable on 4k televison.
Thank you.

**Comment by ivarbrandt** [comment]
This has been completed for next update. If you would like to get a sneak peak before the official release you can do so in my test repo. The changes are in `1.0.15f`.

In order to see the bigger size widgets just go to a currently configured widget, and click Display type. There you'll see three new widgets, BigPoster, BigLandscape, and BigLandscapeInfo.

Also the InfoWall, WideInfoWall, Wall, and WideWall views have been updated to use the bigger artwork.

**Comment by TwilightMercy** [comment]
Thank you, looks really good! was worth the wait : )

> Also the InfoWall, WideInfoWall, Wall, and WideWall views have been updated to use the bigger artwork.

Will `View_51_Poster.xml` be changed also?

**Comment by ivarbrandt** [comment]
No `View_51_Poster.xml` will not be updated. That is the only view that will keep the smaller poster size.

**Comment by IG2022** [comment]
> This has been completed for next update. If you would like to get a sneak peek before the official release you can do so in my test repo. The changes are in `1.0.15f`. You'll also need the latest version of the the Helper `0.6.14c`.
> 
> In order to see the bigger size widgets just go to a currently configured widget, and click Display type. There you'll see three new widgets, BigPoster, BigLandscape, and BigLandscapeInfo.
> 
> Also the InfoWall, WideInfoWall, Wall, and WideWall views have been updated to use the bigger artwork.

Thanks so much for adding this option! I don't have your test repo installed but I'll go ahead and install it and take a look later when I get home.

**Comment by ob89** [comment]
Thank you for the update.
I just tested it and I personally liked it when it was even bigger. Maybe I am the minority from the people who asked for it so I am not going to stress for it to be even bigger.
I would like to know what the other people who asked for it think even if you are not going to make it even bigger.
If @IG2022  @Nuklear92  @TwilightMercy  already tested it what do you think on the current size compared to what it used to be on older versions?

Thanks you for making the change will change for the bigger size and use the beta version for the time being.

**Comment by TwilightMercy** [comment]
I think that the transition from 6 posters in screen to 5 is great and the change is meaningful for large TVs with the skin. 

I also think that 4 posters in screen (“Bigger” display type) will be good option:)

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/9a305307-2f04-491d-8758-5a1397551c8b)
