### ISSUE TITLE
Feature Request : OMDB integration

### ISSUE THREAD

**Issue by abhi98228** [ivarbrandt/skin.fentastic#47]
Thanks for your work! I wish one more cool and informative feature. If you could add OMDB integration to show ratings for movies.

**Comment by Nuklear92** [comment]
This would be nice if they show for example the in the "List" media view which has the big posters, maybe inside the poster itself in one of top or bottom corner of it. Or maybe on the left side panel below the title and info in a compact nice way that doesn't look off or unaligned with the rest of the info that's presented. Just throwing guesses in the air. 😅 perhaps the Dev itself would find a better place for it to display them. Obviously, not every media view available is capable of showing this OMDb Ratings info, but I'm sure at least for now the "List" media view has potential to show this rather nicely. 👍

**Comment by ivarbrandt** [comment]
I have thought of implementing ratings but I haven't decided yet whether or not I want to.

**Comment by Nuklear92** [comment]
> I have thought of implementing ratings but I haven't decided yet whether or not I want to.

It's always great to have OMDb ratings as it gives a quick perspective of how good or bad a movie or tv show can be at a first glance. Even though film and tv shows are subjective and if someone doesn't like something another can. It will still help on deciding if you wanna take time off your day to spend it watching a particular title. 

That's my humble opinion about OMDb ratings. 🙂

**Comment by TwilightMercy** [comment]
Where is current rating coming from?

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/9c626265-dce3-420f-a57e-fe61fd84fa1b)

**Comment by abhi98228** [comment]
![IMG_1984](https://github.com/ivarbrandt/skin.fentastic/assets/7881952/271fd876-66c7-4394-9f58-7a59c3577794)

I just added a prototype on how to ratings could be shown. I think this feature would make the skin perfect.

**Comment by ivarbrandt** [comment]
> It's always great to have OMDb ratings as it gives a quick perspective of how good or bad a movie or tv show can be at a first glance. Even though film and tv shows are subjective and if someone doesn't like something another can. It will still help on deciding if you wanna take time off your day to spend it watching a particular title.
> 
> That's my humble opinion about OMDb ratings. 🙂

@Nuklear92 
I understand this perspective. It's not whether or not they will be useful that's a deciding factor in whether or not I will add them, it's the overall complexity they would introduce. 

> Where is current rating coming from?

@TwilightMercy 
The current rating comes from TMDb.

>  just added a prototype on how to ratings could be shown. I think this feature would make the skin perfect.

@abhi98228 
I appreciate the enthusiasm but that's not the best place to put them as the poster size can vary.

**Comment by TwilightMercy** [comment]
Asking out of lack of knowledge- what’s wrong with the famous TMDb?

**Comment by ivarbrandt** [comment]
> Asking out of lack of knowledge - what’s wrong with the famous TMDb?

There nothing inherently wrong with TMDb ratings. In my opinion they are pretty accurate. It's more a matter of user preference. All ratings, no matter the source or how many users/critics they have, are subjective.

**Comment by ivarbrandt** [comment]
I have decided that I do want to implement the OMDb ratings into the skin. However, because of the complexity and time I believe this will take, I'm not sure which update this feature will land on. 

Right now there are some other ideas I want to implement and I feel like ratings are the icing on the cake. But I'm still working on the cake lol.

So just know that it's on my TODO list and I'm going to do my best to get it done, I just don't know when. 

I'll be closing this issue until I begin working on it in the future.

**Comment by SoulReaverFan** [comment]
I know this is still WIP but really nice to see the ratings appearing in this skin. I just wanted to let you know that the ratings don’t seem to update when focusing a new widget item on the home menu so it always displays the same rating when scrolling on the same row of items. It does update when scrolling down to a new category row of widget items though. Just wanted to let you know on the off-chance that you hadn’t noticed this behavior. 

Thanks again for the great work and have a good one! 👍

**Comment by ivarbrandt** [comment]
Yes, I am aware of that. They also don't work within Fen yet. There's quite a bit that still needs to be fixed. I just haven't had the time.

**Comment by ivarbrandt** [comment]
Finished for next update.

**Comment by ivarbrandt** [comment]
1.0.19 is now up. Enjoy!
