### ISSUE TITLE
Visual bug on sidebar 

### ISSUE THREAD

**Issue by les017** [ivarbrandt/skin.fentastic#48]
Been using Fentastic since day one and have loved the progress! Thank you.

On home screen when I scroll up to the tools menu and use one of the tools, the top side bar menu item remains highlighted. Please see attached pic.

Visually it implies that (in my case) TV SHOWS is active, yet when I click the power button will engage.

It's not huge deal, I just need to remember this behavior and scroll down one slot. But still thought you might want to correct. This happens on all my Nvidia Shields.

Thanks again

![PXL_20230725_120727235](https://github.com/ivarbrandt/skin.fentastic/assets/236296/55c2a87b-1741-48d1-ab5b-ea5bf88b6cdc)

**Comment by les017** [comment]
Ah yes, I neglected to say that it IS only after a skin reload.


Thanks,
Evan

**Comment by ivarbrandt** [comment]
This is a bug that I've seen for a long time. It even happens on the default Estuary skin. 

I've tried to fix this many times and I haven't had any success.

I have a different idea that I haven't tried yet so I'll take a look at this again soon.

**Comment by les017** [comment]
My man! Thanks for everything


Thanks,
Evan

**Comment by les017** [comment]
Dude.... wonderful thanks


Thanks,
Evan
