### ISSUE TITLE
[Request] FENtastic 1.0.15a - Titles for widget labels Hebrew bug

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.fentastic#49]
Hi friend,

Sorry to bother you again with Hebrew language issues : )

I tested `FENtastic 1.0.15a` from test repo, and new title label for current widget is great addition : )

When it will be officially released, I will update it in my fork. I was wondering if you can help me solve the Hebrew language issue here:

As you can see here, for English widget name "Trending", there is no issue: (also for FEN Metadata language Hebrew - it looks correct)
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/8b047b0f-8c8f-4959-a616-140e0adae8f8)

When the widget name is in Hebrew language ("פופולרים" = "Trending" in Hebrew), I see this:
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/b3f49564-9736-42b6-b63c-f43131a245a6)

Another example:
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/ccb0b6a6-a038-4c00-a0f4-f6c0db975ae2)

It seems that the widget name is appearing twice, should be:
Guardians of the Galaxy Vol .3 | פופולרים

but the "פופולרים" string ("Trending") appears twice on the beginning

If you want to test it yourself, simply rename any widget name to Hebrew name:
פופולרים

If any specific Hebrew fix is needed here, which you probably you don't need in your official version, I can put it only in my fork no worries.

Thank you very much!

**Comment by ivarbrandt** [comment]
This feature isn't complete in `1.0.15a`. It completely broke the stacked widgets among other things.

I have since fixed it so wait for `1.0.15b` to drop. Hopefully that version will also have fixed your issue.

**Comment by TwilightMercy** [comment]
Thank you, I will soon test my issue with 1.0.15d

Side note - from changelog: "- Removed alternate InfoPanel" - no :(  T.T

**Comment by ivarbrandt** [comment]
> Side note - from changelog: "Removed alternate InfoPanel" - no :( T.T it's perfect

Two reasons I got rid of it:

    1. Takes up too much space.
    2. Format doesn't allow for dynamic handling of items based on visibility conditions

**Comment by TwilightMercy** [comment]
> Format doesn't allow for dynamic handling of items based on visibility conditions

Can you explain what you mean? Isn't it the same parameters used but in different "design"? (with **[CR]** separators instead of **"•"** character)

Anyway no worries, I updated my fork latest version while keeping `Use alternate format for InfoPanel` setting, and added Mpaa rating (last line):
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/2feac81b-330c-4e25-b37b-c5e7692c4262)


--------------------------------------------------------------------------------------------------------------------------------

Regarding the main issue - it's fixed and formatted correctly for Hebrew language - thank you very much!

**Comment by ivarbrandt** [comment]
> Regarding the main issue - it's fixed and formatted correctly for Hebrew language

Awesome! Glad that it got fixed in the process.

> Can you explain what you mean? Isn't it the same parameters used but in different "design"? (with [CR] separators instead of "•" separators)

Sure. It is the same `$INFO[]` (infolabels) but the design is different.`[CR]` creates a new line which means that if ANY of the infolabels are empty then there would be an empty space using the alternate InfoPanel. But because the normal infopanel doesn't use `[CR]`, I can make the labels dynamic and it won't matter if for example some items don't have a MPAA rating because the InfoPanel can auto-adjust. 

This is my preference as it makes it so that I can add labels to the InfoPanel and not worry about whether or not it will look good if some of the infolabels are empty.

**Comment by TwilightMercy** [comment]
I see and understand, I noticed myself some empty MPAA rating labels in alternate infopanel.
What about simple solution of "Unknown" string for null values? replacing the empty space

**Comment by ivarbrandt** [comment]
I don't think that is the best solution because the infolabels can't auto-collapse no matter what if you're using [CR].

I however have not tried that though so try it out and lemme know how it goes.

**Comment by TwilightMercy** [comment]
Hi,

using latest test version 1.0.15m, after you successfully fixed Movies/TV Shows posters [here](https://github.com/ivarbrandt/skin.fentastic/issues/49#issue-1827360298),

I noticed same text issue here in collections / actors posters view (using search results window):


![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/9d3cf481-301b-4d28-9a78-a0db5bce6d17)

for all of the rest search methods - movies / tv shows / IMDb keywords / Trakt lists - no issue

**Comment by ivarbrandt** [comment]
Because of the way it is set up a fix for that will be much harder. At least I think it will.

It is working fine for English and pretty much all other languages.

**Comment by TwilightMercy** [comment]
Is the fix different from the way you fixed [here](https://github.com/ivarbrandt/skin.fentastic/issues/49#issuecomment-1656642016)? (Movies/TV Shows labels

**Comment by ivarbrandt** [comment]
Yes it will have to be different.

**Comment by TwilightMercy** [comment]
I see, it's really minor since not using collections / actors searches that much so no problem friend
