### ISSUE TITLE
Feature Request - Show Release Year In Home Page Info Panel

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.FENtastic#5]
Hi,
As continuation of this issue - https://github.com/ivarbrandt/skin.FENtastic/issues/4

It looks great! very clean and helpful.
Only thing missing for me is release year, if possible to add. 
Thank you very much!

![image](https://user-images.githubusercontent.com/29895680/228947613-0df75aa5-d793-4275-81c0-2371ef1857bf.png)

**Comment by ivarbrandt** [comment]
The release date is shown in the bottom right of the screen. Does that work for you?

**Comment by TwilightMercy** [comment]
Yes I see it - 

![image](https://user-images.githubusercontent.com/29895680/228986221-81f199c3-d75b-467f-9fe3-30a2dfa854ab.jpeg)

in my opinion it’s very small and “missable” down there, the big left info panel is great and catches the eye. Can the release year/date (I think year is enough) be added there?

**Comment by TwilightMercy** [comment]
Similar to


![](https://user-images.githubusercontent.com/29895680/227797529-4c82c7f5-ef8e-4d96-b47e-4cf6c4eadcce.png)

**Comment by TwilightMercy** [comment]
TOP :)

**Comment by ivarbrandt** [comment]
I did too. Then the bottom started to grow on me because it is more compact.

**Comment by TwilightMercy** [comment]
Isn’t the top option with the blue text color more organized? (by lines)

Anyway whatever option you’ll choose, it will be blessed :) (or make two options configurable if you want)

**Comment by ivarbrandt** [comment]
Ok I'll add the release year in and make the format optional.

**Comment by TwilightMercy** [comment]
Thank you very much! appreciated. 

I’m running Kodi + Fen build with telegenic group of close to 4k members, currently using Estuary skin with simple favorites page: (Language is Hebrew)

![image](https://user-images.githubusercontent.com/29895680/229108564-9f171a20-09ee-46c9-b671-9fc651df6fcf.png)


Soon I will to move to FENtastic :)

**Comment by ivarbrandt** [comment]
Oh wow. I think your members will REALLY appreciate widgets 😃

**Comment by TwilightMercy** [comment]
> > I’m running Kodi + Fen build for Telegram group of close to 4k members
> 
> That's exciting! I think your members will REALLY appreciate widgets 😃

Indeed!

**Comment by ivarbrandt** [comment]
Completed for next update.

**Comment by TwilightMercy** [comment]
> > I’m running Kodi + Fen build for Telegram group of close to 4k members
> 
> That's exciting! I think your members will REALLY appreciate widgets 😃

Hi,
Here's my first "Pilot" for the build with FENtastic : )
Everything is in Hebrew

https://www.veed.io/view/30c6fcd5-77b5-4d65-9e9a-ba3fbf45bf23?sharingWidget=true&panel=share

**Comment by ivarbrandt** [comment]
Looking clean. 

Idk if you're aware of this but I added Custom Search Options from the home window. Just click the Search icon and you'll get a Search dialog for all of Fen's search items. This way you don't have to use a category widget for the Search function.

**Comment by TwilightMercy** [comment]
Thank you, I didn't notice that.
