### ISSUE TITLE
Alternate InfoPanel auto collapse new lines for empty params

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.fentastic#50]
Hi, continuing this discussion: https://github.com/ivarbrandt/skin.fentastic/issues/49#issuecomment-1656747157

It is done and working well - if no MPAA Rating is available - the line doesn't appear at all. This can be done for all alternate InfoPanel variables. Here's an example of MPAA rating code:

**Screenshot - when MPAA rating exists:**
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/522c3380-5b18-409d-9177-75bd79bab59d)

**Screenshot - when MPAA rating NOT exists:**
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/ac2b8cdb-c900-499f-8b20-45c2862de6c4)

Code:
Variables.xml - under `<!-- MY VARIABLES -->`

```
<!-- MPAA Rating -->
<variable name="MPAA_Rating_Param">
<value condition="!String.IsEmpty(ListItem.Mpaa)">[CR][COLOR button_focus][B]Age Limit:[/B] [/COLOR]$INFO[ListItem.Mpaa]</value>
</variable>
```

Example Movies alternate InfoPanel variable:

`$VAR[MPAA_Rating_Param]` is located between `$INFO[ListItem.EndTime]` param and between: `[CR][CR]` (before tagline and plot).

```
<value condition="![ListItem.IsCollection + String.IsEmpty(ListItem.Plot) + String.IsEmpty(ListItem.Genre)] + String.IsEqual(ListItem.DBtype,movie) + Skin.HasSetting(Enable.AlternateInfo)">[COLOR button_focus][B]Network:[/B] [/COLOR]$INFO[ListItem.Studio][CR][COLOR button_focus][B]Released:[/B] [/COLOR]$INFO[ListItem.Year][CR][COLOR button_focus][B]Genre:[/B] [/COLOR]$INFO[ListItem.Genre][CR][COLOR button_focus][B]Director:[/B] [/COLOR]$INFO[ListItem.Director][CR]$INFO[ListItem.EndTime,[COLOR button_focus][B]$LOCALIZE[31080]:[/B][/COLOR] ]$VAR[MPAA_Rating_Param][CR][CR]$INFO[ListItem.Tagline,[I],[/I][CR][CR]]$INFO[ListItem.Plot][CR][CR]</value>
```

`$VAR[MPAA_Rating_Param]` itself is built from [CR] + label + value, example output:

[CR]**Age Limit:** PG-13

This can be done for all variables so they can not appear if they're empty, and the final infopanel var will look like (example):
```
<value condition="![ListItem.IsCollection + String.IsEmpty(ListItem.Plot) + String.IsEmpty(ListItem.Genre)] + String.IsEqual(ListItem.DBtype,movie) + Skin.HasSetting(Enable.AlternateInfo)">$VAR[Studio_Param]$VAR[Year_Param]$VAR[Genre_Param]$VAR[Director_Param]$VAR[EndTime_Param]$VAR[MPAA_Rating_Param]$VAR[Tagline_Param]$VAR[Plot_Param]</value>
```

What do you think?

**Comment by Tikipeter** [comment]
When calling for an infolabel, you can utilize 2 commas after the call. i.e

$INFO [Listitem.Genre,,]

After the first comma, you put any prefix string, and after the second comma you put any suffix string.

The prefix and suffic strings will only appear if the infolabel has a value, orherwise they will be ignored.

This is the most correct way to deal with this sort of thing.

**Comment by ivarbrandt** [comment]
> What do you think?

I think it makes perfect sense that you can use variables to conditionally display parts of the InfoPanel as this is what variables were designed for.

I would however recommend sticking to the formatting that Peter provided above so you can format the labels using whatever prefix and suffix you choose. This is exactly how I was was formatting the InfoPanel.

> After the first comma, you put any prefix string, and after the second comma you put any suffix string.

I did not know about the second comma. I was using one comma for all of my infolabels.

This helps a lot man thanks!

**Comment by TwilightMercy** [comment]
> I would however recommend sticking to the formatting that Peter provided above so you can format the labels using whatever prefix and suffix you choose. This is exactly how I was was formatting the InfoPanel.

Will do, thank you both. I will use this method in fork for the alternative InfoPanel.
Just to confirm, you are not interesting in bringing it back officially right? that's totally fine, just to know.

**Comment by ivarbrandt** [comment]
Correct, I don't have any interest in bringing it back. Especially now that there are more infolabels in the InfoPanel.

Is that why you opened this issue?

**Comment by TwilightMercy** [comment]
> Is that why you opened this issue?

No, just to know a better approach for alternative InfoPanel code.

Thank you both for the help.

**Comment by ivarbrandt** [comment]
You're welcome :)

**Comment by ivarbrandt** [comment]
> Just to confirm, you are not interested in bringing it back officially right? that's totally fine, just to know.

I wanted to let you know that I'm bringing the alternate InfoPanel back as there are more people that prefer it. It's going to need a full rewrite though to make it more dynamic between the different formats.

https://github.com/ivarbrandt/skin.fentastic/issues/53

**Comment by TwilightMercy** [comment]
Thank you! comforting to know I wasn't the only one using it.. 😅

As for the code, I've used Tikipeter's method (commas for prefix/suffix) to make MPAA rating dynamic if not exists, and it works well.

---------------------------------------------------------------------------------------------------------------------
As for your question there, I think option A is good (for both Seasons + Runtime).
For season it will keep the format the same with the other variables.

If you don't mind me sharing, In my fork, the alternate InfoPanel currently looks like this:

**Movie:**
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/2066f384-cb79-40e6-926d-0bcbc38a9936)

**TV Show:**
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/55b28d29-40df-48ae-8005-522c01b644f8)

**Episode:**
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/1240b88c-95e2-49ed-9846-36634850a1f6)

**Comment by ivarbrandt** [comment]
> As for the code, I've used Tikipeter's method (commas for prefix/suffix) to make MPAA rating dynamic if not exists, and it works well.

I will use that too but what I meant by making it dynamic is creating variables that can be used with both versions of the InfoPanel. I know how to do it I just gotta rewrite the whole thing.

> For season it will keep the format the same with the other variables.

Yup, I agree.

> If you don't mind me sharing, In my fork, the alternate InfoPanel currently looks like this (also made the blue "headers" labels in bold):

Some of the labels will be in a different order but this is exactly how I'm going to bring it back. Bold labels and everything.

**Comment by TwilightMercy** [comment]
Great, good luck!

**Comment by ivarbrandt** [comment]
It's done. Changes will be in `1.0.16a`.
