### ISSUE TITLE
Strange behavior not sure how to fix it 

### ISSUE THREAD

**Issue by Santaklawz** [ivarbrandt/skin.fentastic#51]
I installed fentastic skin looks good then tried playing a tv show which I added to my favorite then had a kodi crash I just added trending and latest release to movie widget and up next and in progress to tv show very confusing can someone please tell me how I can make the skin stable so I don't crash out of kodi? My device is xgimi elfin projector which runs fen on estuary perfectly

**Comment by TwilightMercy** [comment]
Read this under skin settings 

![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/6ea43d50-82c5-45d9-b051-9698fe03be87)

**Comment by Santaklawz** [comment]
I will go through it tonight thx

**Comment by Santaklawz** [comment]
Also when I installed the skin it replaced my file manager in settings with skin settings is this normal and where is my file manager so I can install addons

**Comment by Santaklawz** [comment]
I read what it says to avoid crashes how do I reverse this setting if it doesn't help me set language invoker to true?

**Comment by ivarbrandt** [comment]
Either don't use widgets with the skin or disable the reuselanguageinvoker setting inside Fen.

**Comment by Santaklawz** [comment]
Where is the reuselanguageinvoker setting in fen? Thank you for your time and effort

**Comment by ivarbrandt** [comment]
I'm going to double check to make sure I've left EXACT instructions on how to do this in the 'Tip:Crashes' menu item.

If I find that I have I will close this issue.

**Comment by Santaklawz** [comment]
Thanks can I reverse this setting by pressing the same thing?

**Comment by ivarbrandt** [comment]
Yes
