### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by Santaklawz** [ivarbrandt/skin.fentastic#52]
I added a tvshow to my favorites and after installing the skin I played part of the episode and exited the episode at which point kodi crashed this behavior doesn't happen when I access the episode through fen directly or through a widget only through favorites thanks so much for a great skin

**Comment by ivarbrandt** [comment]
This is not enough information to go on. Also, there isn't any part of the code related to favorites that could be causing crashes.

Do you have a log or something I can look at?

Also, did you try disabling the languageinvoker in Fen settings like I showed you yesterday?

**Comment by Santaklawz** [comment]
Thanks so much for your help 
I am referring to the favorites tab in kodi itself I didn't try language invoker because I don't want slowdown in fen and there is no problem with play from widget or fen addon only through kodi favorite tab
What log would you like to see?

**Comment by ivarbrandt** [comment]
Stop using favorites for episodes. Use widgets or Fen directly.

**Comment by Santaklawz** [comment]
Hi I tried some more it seems to random crash now even when I  play from widget or fen 
Anyway where is the menu for widget limit in the skin I found it on fen but I read that there is a widget limit for the skin I couldn't find it on skin settings what menu is it on?

**Comment by ivarbrandt** [comment]
There isn't a widget limit option in the skin anymore. 

Widget limits are set in Fen settings.
