### ISSUE TITLE
Request to bring back a few features

### ISSUE THREAD

**Issue by Omarscomin** [ivarbrandt/skin.fentastic#53]
Hey there! Thank you so much for the latest update of FENtastic! I’m loving the bigger poster size, the bigger font, and the fact that titles display when you hover over a movie or tv show! Great work!😁

I was wondering if you might consider bringing back the following features. If not, it's no biggie!

1. The second display option for the info panel. It flowed better and was a lot easier on my eyes. 

2. The percent sign after the percentage of a movie/episode that has been watched. It looks a little strange and confusing, especially when you have TMDB ratings enabled. A friend of mine immediately asked what the 2 different numbers meant. 

3. The option to have the icons next to “Movies” and “TV Shows”. It looks a little plain without them. 

4. The option to disable the icon silhouettes on category widgets. They looked cleaner without them, IMO.  

Thanks again for your hard work, and no worries at all if you aren’t interested in implementing any of my requests! :)

**Comment by ivarbrandt** [comment]
1. I'll think about it as I've had someone else ask for the same thing. How is it easier on your eyes?

2. The percent sign isn't coming back as I would need to resize or recreate 6 different textures. I've made it simple to tell which is the percent watched as it only appears if the widget or item is focused.

3. The main menu without icons looks a lot cleaner in my opinion. It also makes it so that I don't have to add code for a customizable icon for when I add additional sections 😃 

4. Yeah these look way too cool so they're staying. I did make it so that the icons disappear when an item is focused in order to maintain legibility.

Thank you for your input and suggestions.

**Comment by Omarscomin** [comment]
> 1. I'll think about it as I've had someone else ask for the same thing. How is it easier on your eyes?
> 
> 
> 
> 2. The percent sign isn't coming back as I would need to resize or recreate 6 different textures. I've made it simple to tell which is the percent watched as it only appears if the widget or item is focused.
> 
> 
> 
> 3. The main menu without icons looks a lot cleaner in my opinion. It also makes it so that I don't have to add code for a customizable icon for when I add additional sections 😃 
> 
> 
> 
> 4. Yeah these look way too cool so they're staying. I did make it so that the icons disappear when an item is focused in order to maintain legibility.
> 
> 
> 
> Thank you for your input and suggestions.

The info panel is definitely the part I care about the most, so I'm a happy camper!![image](https://github.com/ivarbrandt/skin.fentastic/assets/129215684/27b209b9-e7b3-4dd8-a9cd-db1e7425cadb)

The attached picture shows what I'm talking about. Things just doesn't always flow very well. "Gore" kinda looks like part of the movie genres, as opposed to the director's name. The other info panel would have displayed the info like this:

•2003
•PG-13
•Adventure/Fantasy/Action
•Gore Verbinski
•2 hr 23 mins
•Ends at 7:40 PM

Thank you so much for your quick reply and for the consideration! Really appreciate you!😁

**Comment by VelimirSaban** [comment]
I would also like to see more cleaner info panel. It would be much easier if each label had its fixed place always one below the other.

**Comment by ivarbrandt** [comment]
> Please? I'll buy you a beer, coffee, a car, a plane, a trip to space for it? ;)

I'll take the car and the trip to space. Pass on the Titanic lol. 
Btw, I will be adding ratings in the future. Probably not in that format though. I don't know which version they will fall in as I'm currently quite busy.

I will add the alternate InfoPanel back in. I need your opinions though. 

For tvshows would you prefer to see:

Option A
**Seasons:** 4
or
Option B
**4** seasons

And for tvshows and episodes would you prefer to see:

Option A
**Runtime:** 47 mins 
or 
Option B
**Runtime:** 47 min episodes

**Comment by Omarscomin** [comment]
> > Please? I'll buy you a beer, coffee, a car, a plane, a trip to space for it? ;)
> 
> 
> 
> I'll take the car and the trip to space. Pass on the Titanic lol. 
> 
> Btw, I will be adding ratings in the future. Probably not in that format though. I don't know which version they will fall in as I'm currently quite busy.
> 
> 
> 
> I will add the alternate InfoPanel back in. I need your opinions though. 
> 
> 
> 
> For tvshows would you prefer to see:
> 
> 
> 
> Option A
> 
> **Seasons:** 4
> 
> or
> 
> Option B
> 
> **4** seasons
> 
> 
> 
> And for tvshows and episodes would you prefer to see:
> 
> 
> 
> Option A
> 
> **Runtime:** 47 mins 
> 
> or 
> 
> Option B
> 
> **Runtime:** 47 min episodes
> 
> 
> 
> 

I think I like Option A better, for both. I would be happy with either though. Thank you so much for doing this!

**Comment by Omarscomin** [comment]
> I've given some thought to what actually matters depending on whether it's a series, movie, or episode. This is how I would put it, based on all my experience:
> 
> 
> 
> TV Shows in general:
> 
> 
> 
> First Aired • 2003
> 
> Created by: Vince Gilligan
> 
> Genre • Adventure/Fantasy/Action
> 
> Rating • PG-13
> 
> Seasons: 4
> 
> Status: Returning Series or Ended.
> 
> Critics • IMDb 6.7 RT 77% MC 67
> 
> 
> 
> TV Shows episodes:
> 
> 
> 
> Aired • 7.8.2023
> 
> Directed by • Gore Verbinski
> 
> Written by • Gore Verbinski
> 
> Genre • Adventure/Fantasy/Action
> 
> Rating • PG-13
> 
> Runtime • 44 mins
> 
> Critics • IMDb 6.7 RT 77% MC 67
> 
> 
> 
> Movies:
> 
> 
> 
> Year • 2003
> 
> Director • Gore Verbinski
> 
> Written by • Gore Verbinski
> 
> Genre • Adventure/Fantasy/Action
> 
> Rating • PG-13
> 
> Runtime • 2 hr 23 mins
> 
> Critics • IMDb 6.7 RT 77% MC 67
> 
> 
> 
> "Ends at • 7:40 PM" for me this is optional if we have Runtime. But if you have space, why not.
> 
> "Critics • IMDb 6.7 RT 77% MC 67" when you are ready to implement Critics, put them in the final row.
> 
> 
> 
> And... that's it. I'll try to book a trip to space for you ;)
> 
> 

He gave us 2 options to choose from, didn't he? I'm confused by your comment and I feel like it's pretty disrespectful. Hopefully I'm wrong.....

Also, I like the "Ends at x:xx"

**Comment by VelimirSaban** [comment]
My goal was not at all to be disrespectful but to give my suggestion to this part of the skin. 
My answer to options A and B can be found in the attached examples. We agree here and I think option A is better.

**Comment by ivarbrandt** [comment]
I vote Option A for both too. It's settled then. Here's what the alternate InfoPanel will look like:

Movies

![movies](https://github.com/ivarbrandt/skin.fentastic/assets/54084201/879bd45b-05a8-4b6a-a2e0-a82c48e386a5)

TV Shows

![shows](https://github.com/ivarbrandt/skin.fentastic/assets/54084201/46d175f8-68ad-4b9e-abbd-954f811c55a2)

Seasons

![seasons](https://github.com/ivarbrandt/skin.fentastic/assets/54084201/62b475cc-5eb5-4ef7-8b3f-ae7af0aec460)

Episodes

![episodes](https://github.com/ivarbrandt/skin.fentastic/assets/54084201/95d6a8bf-4628-406c-9d9c-1ff22808a391)

Also, I thought about what you said, @Omarscomin, and I figured out a way to reuse some of the textures I already have in the skin in order to bring the percent sign back to progress. Here's what it will look like:
 
![progress](https://github.com/ivarbrandt/skin.fentastic/assets/54084201/5bdd2789-f292-46e1-a044-103178aff97b)

**Comment by Omarscomin** [comment]
> I vote Option A for both too. It's settled then. Here's what the alternate InfoPanel will look like:
> 
> 
> 
> Movies
> 
> 
> 
> ![movies](https://github.com/ivarbrandt/skin.fentastic/assets/54084201/879bd45b-05a8-4b6a-a2e0-a82c48e386a5)
> 
> 
> 
> TV Shows
> 
> 
> 
> ![shows](https://github.com/ivarbrandt/skin.fentastic/assets/54084201/46d175f8-68ad-4b9e-abbd-954f811c55a2)
> 
> 
> 
> Seasons
> 
> 
> 
> ![seasons](https://github.com/ivarbrandt/skin.fentastic/assets/54084201/62b475cc-5eb5-4ef7-8b3f-ae7af0aec460)
> 
> 
> 
> Episodes
> 
> 
> 
> ![episodes](https://github.com/ivarbrandt/skin.fentastic/assets/54084201/95d6a8bf-4628-406c-9d9c-1ff22808a391)
> 
> 
> 
> Also, I thought about what you said, @Omarscomin, and I figured out a way to reuse some of the textures I already have in the skin in order to bring the percent sign back to progress. Here's what it will look like:
> 
>  
> 
> ![progress](https://github.com/ivarbrandt/skin.fentastic/assets/54084201/5bdd2789-f292-46e1-a044-103178aff97b)

I love it so much! Sooo much more organized and easy on the eyes! And thank you so so much for bringing back the percent sign too! I had already gotten used to the idea of not having it, but this is even better😁YOU DA BEST!!

**Comment by ivarbrandt** [comment]
I'm glad you like it! I prefer the other format because it is more compact but to each their own.

I also really like the percent sign. It looks much cleaner than even before.

**Comment by Omarscomin** [comment]
> I'm glad you like it! I prefer the other format because it is more compact but to each their own.
> 
> 
> 
> I also really like the percent sign. It looks much cleaner than even before.

Wow, that was an asshole thing for me to say. I should've said "it's so much easier on _my_ eyes." My apologies. 

Speaking of things being "easy on my eyes", I wanted to give you some props for the fact that the _entire_ plot displays in the info panel, unless it's...like..._ridiculously_ long. I'm not fond of the way most skins only show 1-2 lines of the plot and rely on auto scroll.

**Comment by ivarbrandt** [comment]
> Wow, that was an asshole thing for me to say. I should've said "it's so much easier on my eyes." My apologies.

All good. I knew that you were saying that from your perspective.

> I wanted to give you some props for the fact that the entire plot displays in the info panel, unless it's...like...ridiculously long.

I appreciate that. I didn't really notice it till now that you've mentioned it. Just always felt right to have a plot that you can actually read.

**Comment by ivarbrandt** [comment]
This has been completed for the next update. If you absolutely can't wait for `1.0.17`, then you can get `1.0.16a` from the test repo. I'll be pushing `1.0.17` in a day or two so it's up to you guys and gals what you want to do.

**Comment by Omarscomin** [comment]
> This has been completed for the next update. If you absolutely can't wait for `1.0.17`, then you can get `1.0.16a` from the test repo. I'll be pushing `1.0.17` in a day or two so it's up to you guys and gals what you want to do.

Thank you sooooo much! Doin' the Lord's work!🫶

**Comment by VelimirSaban** [comment]
This is really good! Thank you

**Comment by ivarbrandt** [comment]
The latest version, `1.0.18`, is now available in the main repo.

@Omarscomin 

I added a toggle in Skin settings > Options that makes the icon silhouettes for the category widgets optional.

**Comment by Omarscomin** [comment]
> The latest version, `1.0.18`, is now available in the main repo.
> 
> 
> 
> @Omarscomin 
> 
> 
> 
> I added a toggle in Skin settings > Options that makes the icon silhouettes for the category widgets optional.

Soooo, you literally made all of my feature requests happen? You're the fucking best...
