### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by derrgoo** [ivarbrandt/skin.fentastic#54]
Love the skin and great idea all around! I was wondering if it was possible to be able to create my own sections other than just main TV Shows and Movies? I like to put sports and other sections as well. Is that possible? 

Thanks, 
Groguuu

**Comment by ivarbrandt** [comment]
Currently it isn't possible. But in the next version, `1.0.17`, I'm planning on adding in an additional 3 custom sections. 

The most common requests for the additional sections have included Anime, Live TV, and Sports. But they'll be configurable so you can set them up them however you'd like.

**Comment by derrgoo** [comment]
> Currently it isn't possible. But in the next version, `1.0.17`, I'm planning on adding in an additional 3 custom sections.
> 
> The most common requests for the additional sections have included Anime, Live TV, and Sports. But they'll be configurable so you can set them up them however you'd like.

That would be great…three would be plenty! Looking forward to your update! Thanks for answering.

**Comment by ivarbrandt** [comment]
Actually it'll be `1.0.18` since I need to push a small update for `1.0.17 `

**Comment by derrgoo** [comment]
All keep this open so I can see updates!

**Comment by ivarbrandt** [comment]
Finished for next update.
