### ISSUE TITLE
Resume playing from timestamp prompt not working correctly

### ISSUE THREAD

**Issue by mwryan90** [ivarbrandt/skin.fentastic#55]
Hi there, firstly, thanks for your amazing work with this skin. I can't speak highly enough of it and when I stumbled upon it, it was a revelation.

I have the skin on three devices, a Sony TV, and two Chromecasts with Google TV.
All three devices have this issue.

The issue is that when I resume a TV Show or Movie that I have already made some progress in, the "resume playing from 20:34" prompt doesn't show up, instead, the screen just goes dim as if it is trying to display it but the dialogue window doesn't show. I can simply press enter/OK and it will choose the top option which is to resume from the timestamp, or I can press down and then enter to start from the beginning (as is the second option in that pop-up prompt).

My default option when selecting a movie or show is "show information" rather than play, if that makes any difference. I then obviously press play from the movie/tv show information screen and that is when the problem happens.

I am using Seren rather than Fen too (which by the way works really well in this skin), though I wouldn't expect that to make a difference as Fen/Seren is not being called at that point (as far as I'm aware).

If there's any logging you would like me to do, or if you'd like me to share a video, please let me know. 
To be honest, I expect it must be something in my setup considering that no one else has reported it.

Thanks in advance for any help.

**Comment by ivarbrandt** [comment]
I'm glad you're enjoying the skin.

I want to preface my whole response with the fact that the skin was specifically designed for use with Fen. Since you are using Seren I can't help you out by testing things on my side as I don't have the addon installed.

That being said, I'll do my best to help you figure out what is going on but there's only so much I can do. Especially if the problem lies within Seren itself.

>  though I wouldn't expect that to make a difference as Fen/Seren is not being called at that point (as far as I'm aware).

At this point Seren is definitely being called as the window that you're seeing comes from Seren in order to display the resume options. Fen has a similar window.

Have you tried the default skin Estuary? Are you seeing the same issues there? If you are then the problem lies within Seren.

Have you also tried changing the default action to 'Play' instead of 'Show information' and then tried resuming from a widget or the addon itself?

**Comment by mwryan90** [comment]
Thanks for the quick response.

I tried in Estuary and it worked normally, the pop-up correctly showed. 
I tried changing the default action to Play as well (in Fentastic), and it made no difference.
I started an in-progress show from Seren itself and the same thing happened (pop-up didn't show).

I understand this is probably a low-priority issue and perhaps I should just switch back to Fen! I don't actually remember the reason why I preferred Seren over Fen anymore...

If it's something you're interested in checking out, great, if not, I can definitely live with it!

**Comment by ivarbrandt** [comment]
Yeah to be completely honest I don't really wanna check this out.

I used to use Seren as well. But Fen has overtaken it in terms of features, speed, functionality, and ease of use. I've used Fen for many years with very few issues. Most times the issues were user error lol.

If you find something missing in Fen lemme know. I know the addon pretty well so I might be able to find what you think is missing or you can make a feature request in Tikipeter's repo.

**Comment by mwryan90** [comment]
Haha that's fair enough.

I've set one of my TVs up with Fen and it actually looks pretty good. Maybe I didn't give it enough of a chance previously.

Feel free to close this issue. 

Thanks a lot for your help and speedy replies!

By the way, not sure how feasible this would be but being able to backup and restore config settings would be amazing. I get one TV set up perfectly and it's a bit of a ball ache trying to get the other two the exact same lol.

Cheers.

**Comment by ivarbrandt** [comment]
> By the way, not sure how feasible this would be but being able to backup and restore config settings

I might add this at some point in the future. For now, the configuration for the widgets and main menu items is saved in `userdata/addon_data/script.fentastic.helper/cpath_cache.db`.

Copy that over to your other installs to have the same setup.
