### ISSUE TITLE
Are custom new main menu items working yet in 1.0.18d and e?

### ISSUE THREAD

**Issue by meesterexx** [ivarbrandt/skin.fentastic#60]
Not sure if this new feature is ready yet, but I can't use any of the 3 new custom main menu entries under Skin settings > Main menu items. Whenever I try to set menu path it throws an error in the kodi log:

```
error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
 Error Type: <class 'KeyError'>
 Error Contents: 'custom1'
 Traceback (most recent call last):
   File "C:\Ktest20\portable_data\addons\script.fentastic.helper\resources\lib\default.py", line 3, in <module>
     routing()
   File "C:\Ktest20\portable_data\addons\script.fentastic.helper\resources\lib\modules\router.py", line 40, in routing
     return CPaths(_get("cpath_setting")).manage_main_menu_path()
   File "C:\Ktest20\portable_data\addons\script.fentastic.helper\resources\lib\modules\cpath_maker.py", line 61, in __init__
     self.main_include = main_include_dict[self.media_type][self.path_type]
 KeyError: 'custom1'
```

I've tried on 1.0.18d and 1.0.18e. I've done clean installs each time, it just doesn't work for me.
Windows 11 64 bit, Kodi 20.2 (both main install and portable install).

Also, there's no default label or name shown for the custom items, not sure if that is how it's intended, I thought maybe it would say something like Custom1, etc:
![screenshot00000](https://github.com/ivarbrandt/skin.fentastic/assets/13154733/e28751d2-b8d6-42c0-b61f-0c236bede194)

BTW, the style updates on this latest version look amazing. Will we be able to customize the highlight / selection color from just white?
Thank you, can't wait for the updates !

**Comment by meesterexx** [comment]
Never mind, I just realized I didn't download the latest script.fenhelper.
Sorry!

**Comment by ivarbrandt** [comment]
> Will we be able to customize the highlight / selection color from just white?

Not currently. I chose an off-white because it will look a lot better with any background.

Example:

![Screenshot_20230905-184012](https://github.com/ivarbrandt/skin.fentastic/assets/54084201/7157669c-cd32-4cf7-9ef7-7e6e14338645)
