### ISSUE TITLE
Search results item ratings overlaps name on Collections and Actors rows

### ISSUE THREAD

**Issue by meesterexx** [ivarbrandt/skin.fentastic#61]
Using 1.0.18e and entered my OMDB key in skin settings>options, and noticed in search results that ratings for the previous highlighted item (that has ratings) are overlapping the name on Collections and Actors. I am guessing the value of the ratings variable should be cleared/not displayed when moving to Collections or Actors results row. 

First screenshot below shows issue with it having the rating of the previous item above it :
![screenshot1](https://github.com/ivarbrandt/skin.fentastic/assets/13154733/70a164ef-9596-4572-ae1f-8ad030b50ee8)

Rating of previous highlighted item above it:
![screenshot2](https://github.com/ivarbrandt/skin.fentastic/assets/13154733/f580e17b-a8ec-41bb-a371-4a35b5e6e6bb)

**Comment by meesterexx** [comment]
Quick update, and you may already be aware of this: I noticed a similar behavior on homescreen widgets, the text doesn't overlap, but items that don't have their own rating display the rating of the previous item that did have a rating. 

For example, I have an anime watchlist from the Otaku addon and those items show the ratings of the previous item from the tv shows fen widget that is above it. If I go back up 1 row to the Fen show widget, go over 1 item it correctly picks up the rating for that 2nd item, then if I go back down to the Otaku widget, the item that had ratings from item 1 in the Fen widget now has the ratings from item 2 in the Fen widget.

Thanks!

**Comment by meesterexx** [comment]
Issue resolved with 1.0.18g update. Great work and thank you!!

**Comment by ivarbrandt** [comment]
I'm glad. I fixed it but forgot to reply to your issue.
