### ISSUE TITLE
Actors' images are stretched horizontally compared to the default Kodi skin

### ISSUE THREAD

**Issue by VelimirSaban** [ivarbrandt/skin.fentastic#63]
I noticed that on the info page of movies and series, images of the actors are stretched horizontally compared to the default Kodi skin. I assume that it is due to the aspect ratio of the image and how the image fits into the skin. This is not a problem in the functionality of the skin, of course, but it looks a little strange to me every time I open movie or series info.

Estuary:
![IMG_0196](https://github.com/ivarbrandt/skin.fentastic/assets/59098356/b9b247fc-4153-40c4-b92a-ac7cd856c43a)

FENtastic:
![IMG_0197](https://github.com/ivarbrandt/skin.fentastic/assets/59098356/4a0b211c-8695-45f0-89b6-4d7128159395)

Estuary:
![IMG_0199](https://github.com/ivarbrandt/skin.fentastic/assets/59098356/6dc7cc29-2654-4d12-9440-5bd699fa251d)

FENtastic:
![IMG_0198](https://github.com/ivarbrandt/skin.fentastic/assets/59098356/c0fd0bc1-88ee-4379-8e01-2f39e73613e1)

**Comment by ivarbrandt** [comment]
I'll be honest with you. This is low on my list of priorities of things to fix. 

I never use this window as I always use Fen extras. It's way better and offers more features/functionality.

I recommend you do the same.

**Comment by VelimirSaban** [comment]
Yeah, It’s understandable. I primarily use Umbrella but will try to move to Fen. 👌🏼

**Comment by ivarbrandt** [comment]
Umbrella doesn't have an extras window?

**Comment by VelimirSaban** [comment]
> Umbrella doesn't have an extras window?

Not that I know of. I tried Fen again and it’s great, with extras and all, but I can’t find one important feature/source list from which I create a widget: My TV shows - Upcoming progress:

![IMG_0201](https://github.com/ivarbrandt/skin.fentastic/assets/59098356/86d1df9d-8fc5-46f6-b41e-40895685c60e)
![IMG_0202](https://github.com/ivarbrandt/skin.fentastic/assets/59098356/fb7be92b-5315-4a5b-98ba-660d1bc5ee30)

I like to have a widget that shows me upcoming TV shows which are returning soon and in the future. The only way I can do this with Fen is using Trakt calendar as a widget source but it’s not as simple as in Umbrella. Fen can show adjustable “future days” (30 max), Umbrella is showing all Shows with known returning date.

**Comment by ivarbrandt** [comment]
This has been fixed for next update.

**Comment by VelimirSaban** [comment]
Can you please check, it seems that the "press up to see actor’s info" option to get more details about the actor doesn't work anymore post update? Maybe it's something with my system, I'll try again in the afternoon after work.

**Comment by ivarbrandt** [comment]
I removed that functionality to remove the dependency on Embuary Helper and Embuary Info.

**Comment by VelimirSaban** [comment]
Oh. So the only way to get more information about the actor and the movies he starred in is to go back to the older version of the skin? Can I somehow stay on this version, and manualy configure skin to use embuary helper? How does the original kodi skin do that part? I believe that this is the core functionality of every skin and Kodi experience, and that it should remain here in some way. I know there is Fen extras option, but I am Umbrella user. It just suits me better. Thanks for help.

**Comment by ivarbrandt** [comment]
I'll add the functionality back in.

**Comment by VelimirSaban** [comment]
> [ivarbrandt](/ivarbrandt)

coffee is coming!

**Comment by ivarbrandt** [comment]
I added it back in. I'll push a quick update sometime tomorrow.
