### ISSUE TITLE
Missing / Incorrect ratings icons

### ISSUE THREAD

**Issue by meesterexx** [ivarbrandt/skin.fentastic#64]
Using 1.0.18i (but noticed this earlier) some items have missing or incorrect ratings icons, others display fine:

Missing RT tomato and RT audience  for this rating should be red one, not green low rating one. Also comapred to Fen extras, skin TMDB rating is different:
![screenshot00000](https://github.com/ivarbrandt/skin.fentastic/assets/13154733/a67ec281-2375-4e79-90fa-7199dfd571a9)

You can see in Fen extras that the correct icons are available for this title. I have the same OMDB api key in skin and Fen:
![screenshot00002](https://github.com/ivarbrandt/skin.fentastic/assets/13154733/40872f66-fae2-4377-b2c8-db066d7b770a)

Other items from the same widget (Fen Trending Movies) display correctly so not sure why the missing /incorrect icons:
![screenshot00001](https://github.com/ivarbrandt/skin.fentastic/assets/13154733/4ceef6f6-0a5f-4eea-8474-f7e1c50c1c04)

**Comment by ivarbrandt** [comment]
Have you been updating the test versions as they come out? Because if so, your issues likely stem from earlier versions.

Try deleting the ratings cache located in `addon_data/script.fentastic.helper/ratings_cache.db`. Then restart Kodi.

**Comment by meesterexx** [comment]
That fixed it, thanks!

**Comment by meesterexx** [comment]
closing
