### ISSUE TITLE
Enter OMDb API KEY not working

### ISSUE THREAD

**Issue by Nuklear92** [ivarbrandt/skin.fentastic#66]
As the title says, whenever I try to click the option to enter my OMDb api key. Nothing happens, I tried rebooting Kodi, etc. But nothing seems to bring the option working and prompting the keyboard to add the key. 🤷‍♂️

Everything else seems to work great, and also loving the fresh new look! Thanks for the hard work and dedication you've put into this skin. It gets better and better with each new update. Just this small bug I've encountered so far with The OMDb api key.

**Comment by ivarbrandt** [comment]
It seems like you forgot to update the Helper. Latest version is `0.6.16`.

I'm glad you like the new look!

**Comment by Nuklear92** [comment]
> It seems like you forgot to update the Helper. Latest version is `0.6.16`.
> 
> 
> 
> I'm glad you like the new look!

Oh, crap! Let me take a look. 😅

**Comment by Nuklear92** [comment]
You're right, now it's working! However, I find weird that it didn't updated with the skin. Also, it didn't appear in your repo. I had to manually click on the FENtastic dependencies, then click on the helper to update it separately.

**Comment by ivarbrandt** [comment]
The helper doesn't update with the skin. It's always been a separate update.

**Comment by Nuklear92** [comment]
Oh, I see. Thanks, I'll keep an eye on that one next time. 👍
