### ISSUE TITLE
FENtastic (pre-design updates)

### ISSUE THREAD

**Issue by ivarbrandt** [ivarbrandt/skin.fentastic#68]
It has come to my attention that some of you were not totally thrilled about the new design updates in `1.0.19`. Specifically the color changes and removal of color themes. I completely understand how some of you might feel so I would like to give you the option to go back to the last version of FENtastic right before the design updates took place.

Below you'll see the skin and helper zips. These versions do not contain the ratings architecture but I'm pretty sure they do contain the extra sections. Please keep in mind that these come as is and there won't be any support in the future for them. Also, make sure to disable automatic updates for the skin after you install it to prevent newer versions of the skin overwriting this version.

I'm bummed it didn't work out for some of you but I'm so happy that I get to provide you with an option to go back to a familiar version of the skin that you know and love and feel safe in 😃 

[skin.fentastic-1.0.18a.zip](https://github.com/ivarbrandt/skin.fentastic/files/12614155/skin.fentastic-1.0.18a.zip)
[script.fentastic.helper-0.6.15a.zip](https://github.com/ivarbrandt/skin.fentastic/files/12614156/script.fentastic.helper-0.6.15a.zip)

**Comment by Nuklear92** [comment]
I'm really loving the new design, yeah it would be nice to have more options for the theme colors. But, maybe in a future update you may add those options. As of now, I like the monochrome look. 💙😃
