### ISSUE TITLE
Bubu's Movies widget loads in initial installs (2)

### ISSUE THREAD

**Issue by Decent-Sympathy8066** [ivarbrandt/skin.FENtastic#7]
Users attempt to edit/delete widget unsuccessful - guide requested.

**Comment by ivarbrandt** [comment]
Go into Skin settings > Main menu items > click Remake menus and widgets. Go back to the home screen and the Movie and Show section should be empty. 

Then you can go back into Skin settings > Main menu items to set up your widgets.

**Comment by TwilightMercy** [comment]
Small idea I thought about:
Maybe in addition to Changelog in the skin settings menu, you can add "Guide" or "Tips" show these tips in text inside skin settings

**Comment by Decent-Sympathy8066** [comment]
Okay, done. Thanks

**Comment by ivarbrandt** [comment]
> Small idea I thought about:

Good idea. These steps are only necessary one time though. I'll include these instructions in the next changelog.

**Comment by TwilightMercy** [comment]
> > Small idea I thought about:
> 
> Good idea. These steps are only necessary one time though. I'll include these instructions in the next changelog.

If you’ll have it separate page, you can use it for other future extra guides/tips :)
