### ISSUE TITLE
Clicking side menu items

### ISSUE THREAD

**Issue by 92SJ** [ivarbrandt/skin.fentastic#71]
Hello,

First off just wanna say great skin I'm using it on my tablet and phone and its very nice to be able to use widgets that actually function on these devices. Tried alot of skins and they all had issues. However yours works a treat.

I was just wondering when I set the path for the side menu items would it be possible for me to make this function so it just opens up the widgets from within that menu rather than following the path?

Cheers
SJ

**Comment by ivarbrandt** [comment]
It is possible but this is something I don't want to do. 

What you're suggesting is equivalent to an extra section but it would take the the form of a hub in another window. There are already 5 customizable sections so I recommend you use those for your widget needs.

**Comment by 92SJ** [comment]
No worries pal, I'll have a play about anyway see if I can get it to function slightly different 👍🏻
