### ISSUE TITLE
Need a bit of help testing

### ISSUE THREAD

**Issue by ivarbrandt** [ivarbrandt/skin.fentastic#72]
For those of you that follow the updates from my test repo, I would like to ask for your help.

As of the latest test version, `1.0.19c`, I have implemented a fix for the constant crashing. I've tested it on Android and Windows and so far so good. I would like for some of you to help me test this before I release it to the main repo.

To do this, update to `1.0.19c`, make sure ReuseLanguageInvoker is set to TRUE in Fen, then start playback of any movie/tvshow from directly within Fen or from a widget. After a few seconds stop the playback and then return to the homescreen. If you have stacked widgets you should just see a busy spinner as they reload. I recommend you try this a few times to make sure it isn't crashing at all.

Please let me know in a comment below:

- The device you tested this on
- The operating system (Windows, Android, etc)
- Whether or not your test was successful (did it crash?)
- If it did crash, please let me know if you experienced any strange behavior before it crashed.

**Comment by TwilightMercy** [comment]
Gladly!

Just to confirm, The Kodi version must be 20.2 right?

**Comment by ivarbrandt** [comment]
Any version of Nexus is fine. And yes the ReuseLangugeInvoker should be set to true in Fen.

**Comment by TwilightMercy** [comment]
> Any version of Nexus is fine. And yes the ReuseLangugeInvoker should be set to true in Fen.

I will test it soon and update,
About Nexus version - I remembered your comment in reddit's Kodi 20.2 release notes post:
![image](https://github.com/ivarbrandt/skin.fentastic/assets/29895680/4997f96f-c747-4045-9225-d86e8f9dbab5)

Isn't it relevant?

**Comment by ivarbrandt** [comment]
I was mistaken there. So no I don't think it is relevant. I tested it on a Windows machine with Nexus 20.0 and it still worked.

**Comment by TwilightMercy** [comment]
Kodi version: 20.1
FEN version: 3.2.02
FEN ReuseLangInvoker - On

- The device you tested this on - Windows PC
- The operating system (Windows, Android, etc) - Windows 64 bit
- Whether or not your test was successful (did it crash?) - successful - I tested 5-6 times playing movie (from widgets and also from Fen menu), then stopping playback, going back to the home screen (with BigPoster + stacked widgets configured), the stacked widgets title label reloaded (busy spinner) and 0 crashes.

**Comment by ivarbrandt** [comment]
> Side note

The only only commit you'll need is the hidden addons list. Also, be careful as you update your fork because there were some major changes made to the skin design wise.

**Comment by TwilightMercy** [comment]
> > Side note
> 
> The only only commit you'll need is the hidden addons list. Also, be careful as you update your fork because there were some major changes made to the skin design wise.

As you sent this comment, I've just finished backporting only the hidden addons list commit - and it works like charm, 0 crashes in my 1.0.16 fork!
I'm glad you and Tikipeter figured it out!

**Comment by ivarbrandt** [comment]
@TwilightMercy 

Thank you for your help with this.
