### ISSUE TITLE
[BUG/Issue] WideList view not showing thumbnails when searching local files, debrid files, easynews files, etc. within FEN

### ISSUE THREAD

**Issue by Nuklear92** [ivarbrandt/skin.fentastic#74]
As the title says, the default view of WideList when inside of FEN's Downloads, My Services, or any menu that you normally search for video files, etc. the default view of WideList won't show any thumbnails and you always need to switch it to "Wall Icons" media view in order to see the thumbnails. However, in that media view the file names will be super short and the thumbnails are tiny and you barely see them.

**Comment by ivarbrandt** [comment]
I'm not seeing what you're seeing.

Can you take some screenshots as examples please?

**Comment by Nuklear92** [comment]
> I'm not seeing what you're seeing.
> 
> 
> 
> Can you take some screenshots as examples please?

Okay, here some screenshots step by step of what I mean.

![image](https://github.com/ivarbrandt/skin.fentastic/assets/76958541/9022b40d-7bfe-4e0b-b700-c3ed098a1c57)
![image](https://github.com/ivarbrandt/skin.fentastic/assets/76958541/44d56747-eca8-4577-8df1-a58626ffa2b0)
![image](https://github.com/ivarbrandt/skin.fentastic/assets/76958541/973fb274-4f04-4bff-951d-aff7d0088023)
![image](https://github.com/ivarbrandt/skin.fentastic/assets/76958541/d388b6b3-4dfe-4a8b-87da-9462d3f5711c)
![image](https://github.com/ivarbrandt/skin.fentastic/assets/76958541/57070782-9e98-40c1-ac4a-a953c0be9f6d)
![image](https://github.com/ivarbrandt/skin.fentastic/assets/76958541/4bb24d22-fea5-4755-a3a7-ed4491e407c7)
![image](https://github.com/ivarbrandt/skin.fentastic/assets/76958541/94325d16-8a5f-42bc-9a87-5f3cf08c4b65)

As you can clearly see, when you perform a search for video file links within FEN, My Services, EasyNews. The default view "WideList" won't show any information regarding the thumbnail of the files which they clearly have. In order to view them. You need to change the view to "IconWall" which as you can see show the thumbnails but tiny and you can barely make what they look like, plus they the filenames are 95% shortened pretty much so that media view in general is not much of an use in this case. The right thing would be showing the thumbnail in a bigger way in the left side panel where it says "No Information Available" within the "WideList" view.

**Comment by Nuklear92** [comment]
Thanks! Appreciate all the work and dedication you had been putting to this skin project. 😃💙
