### ISSUE TITLE
Side cards viewtype

### ISSUE THREAD

**Issue by Dadkins918** [ivarbrandt/skin.fentastic#75]
Would you consider adding side cards or cards viewtypes like in AZR?  
![IMG_1040](https://github.com/ivarbrandt/skin.fentastic/assets/125222746/3c1f5ca7-2de6-42d8-8861-0859721f6125)
![IMG_1039](https://github.com/ivarbrandt/skin.fentastic/assets/125222746/bb848f1b-9ce6-47c0-a21d-90ba18e239b9)

just a silly cosmetic request.. really like those views for some reason.  Understandable if you don’t want to waste your time on it.

awesome skin either way, really appreciate the work you’ve put into it!

**Comment by ivarbrandt** [comment]
I'm not going to be adding any more views to the skin. If anything I'll be removing some soon.

**Comment by TwilightMercy** [comment]
> I'm not going to be adding any more views to the skin. If anything I'll be removing some soon.

Hope they won't be Poster/Fanart/WideList : )

**Comment by Dadkins918** [comment]
> > I'm not going to be adding any more views to the skin. If anything I'll be removing some soon.
> 
> Hope they won't be Poster/Fanart/WideList : )

Every last one.  Not even basic list.  Find your movies by feel.

**Comment by ivarbrandt** [comment]
> Hope they won't be Poster/Fanart/WideList : )

Nah no worries. I won't be removing any views from the main repo version of FENtastic. 

> Every last one. Not even basic list. Find your movies by feel.

Lmao
