### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by frankycolumbo007** [ivarbrandt/skin.fentastic#76]
Just installed FENtastic on Kodi 20.2 and have TMDB helper, Umbrella, Seren, Dradis and Twilight movie addons. Will dwindle down to 1 or 2 later. My question is when I click on information on a movie, pictures of the actors in said movie appear, but who ever I click on it comes back "No Results Found" no matter what movie addon I'm using. Any way to fix this would be much appreciated thank you.

For what it's worth I think the FENtastic skin is amazing 👍

**Comment by ivarbrandt** [comment]
I recommend you use the Fen extras window. 

I'll be disabling the some of the functionality of that window soon.
