### ISSUE TITLE
No ratings for TV shows 

### ISSUE THREAD

**Issue by DemFaR** [ivarbrandt/skin.fentastic#77]
Hello, I have turned ratings in settings also added my mdblist api but ratings only show for movies not tv shows, I have attached photos 
![20231106_132401](https://github.com/ivarbrandt/skin.fentastic/assets/31755787/96b35723-7278-47e4-bf6b-2f40ea8439ee)
![20231106_132417](https://github.com/ivarbrandt/skin.fentastic/assets/31755787/cf31ce9a-5bcf-45ff-a860-0bc3bd38aaf7)

**Comment by koskal36** [comment]
Hello. In my case the same thing happens when I use wigdets from TMDB HELPER addon.

**Comment by ivarbrandt** [comment]
Do those widgets come from Fen?

**Comment by DemFaR** [comment]
> Do those widgets come from Fen?

They come from tmdb helper

**Comment by koskal36** [comment]
> Do those widgets come from Fen?

Hello !! I have Fen, Umbrella, The crew and TMDB HELPER addons installed, and I use widgets from from each one of them. All works as expected except for TMDB Helper and only in TV SHOWS.

**Comment by ivarbrandt** [comment]
TMDb Helper is not supported.
