### ISSUE TITLE
Scrolling down in Extra info popus

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.FENtastic#8]
Hi,

the Extra Info menu is great addition! I opened CHANGELOG / Setup Guide (from Kodi on Windows 10), and I can't to seem to be able to scroll down the text. Scrolling with mouse, or using keyboards down arrows doesn't work. I don't see scrollbar in the window.

* Edit:  Also on mobile

**Screenshots:**

![image](https://user-images.githubusercontent.com/29895680/229301341-26b1c9ba-e653-4e9c-8b4c-379620cfc059.png)

![image](https://user-images.githubusercontent.com/29895680/229301349-ba279c00-2cf0-4c63-a438-dfcca98e9553.png)

**Comment by ivarbrandt** [comment]
Strange. I can scroll on all of my devices. I don't have a Windows machine to test on though.

Does it work if you restart Kodi and then go back into the Setup Guide or Changelog?

**Comment by TwilightMercy** [comment]
Tried again after restarting. still the same (mouse, keys, etc). and on mobile phone it's the same for me.

**Comment by ivarbrandt** [comment]
Ok I'll take a look at this later.

**Comment by ivarbrandt** [comment]
I couldn't reproduce the behavior you experienced. Nevertheless I made some changes that should fix the scrolling issue for you.

**Comment by TwilightMercy** [comment]
I’m testing from my mobile phone now, not on the computer yet.

I can see now that the scroll bar has been added, and I can long press it and it’s working, but it’s position:

![image](https://user-images.githubusercontent.com/29895680/229370369-cb72b435-1a9d-4b60-a94a-e4fbba4fc61d.png)

**Comment by ivarbrandt** [comment]
The skin is not designed for mobile.

**Comment by TwilightMercy** [comment]
I’ll test from Windows PC and update 👍🏻
