### ISSUE TITLE
Rating not showing on stacked widgets

### ISSUE THREAD

**Issue by jackichad** [ivarbrandt/skin.fentastic#81]
Everything has been working great with the skin but I just noticed this one thing.  The ratings and title logo don't appear on any stacked widgets.  Perhaps it's not meant to work on stacked widgets in which case I apologize.  I just wanted to bring this to your attention.

Here's a few photos as an example of what I'm seeing. First two are normal widgets with ratings and second two are TV and Movie stacked widgets.

https://imgur.com/a/HBO79ew

Thanks.

**Comment by ivarbrandt** [comment]
It should work fine on any widget from Fen/Fen Light.

TMDb Helper widgets do not work well with this skin. The ratings don't work and sometimes the clearlogo gets messed up. I think this is because TMDb Helper provides it's own ratings and artwork.

**Comment by jackichad** [comment]
That makes total sense. I didn't even realize I was using a widget from TMDb Helper.  I'll switch it over to a similar category provided by Fen.  

Thank you very much for the reply and the awesome skin.
