### ISSUE TITLE
Search Feature request

### ISSUE THREAD

**Issue by Cloudman999** [ivarbrandt/skin.fentastic#82]
Thank you for the Fentastic skin @ivarbrandt. It works beautifully with Fen.

Just wondering now Fen Light is available, if it is possible to set it up to work with  the Search button (top left, third button magnifying icon) in your skin.

Currently Search expects to use Fen, not Fen Light.

Many thanks for your consideration.
@Cloudman999

**Comment by ivarbrandt** [comment]
Way ahead of you. I'm planning on adding in search functionality for Fen Light and Umbrella soon.

**Comment by Cloudman999** [comment]
> Way ahead of you. I'm planning on adding in search functionality for Fen Light and Umbrella soon.

Wonderful news @ivarbrandt . Thank you for your prompt reply and truly excellent skin!

Much appreciated
@Cloudman999
