### ISSUE TITLE
(Enhancement)Request for Nested Stacked widgets

### ISSUE THREAD

**Issue by diimaan** [ivarbrandt/skin.fentastic#84]
Hi,

Thanks a lot for your contribution towards the community and continuous improvement. I am not sure this has been requested before or not!
It would be awesome if the option to have nested stacked widgets, similar to Arctic skins. For example, If I have Network or Genre (TV Shows) as Stacked Widget, I can stack the widget again to display season and then again to show episodes. Also this would be useful with Umbrella's Genre Trakt lists (Both Movie and Shows).

Thanks
Diimaan

**Comment by ivarbrandt** [comment]
I've never really understood the point of these kind of widgets. Wouldn't it be faster to go into the addon itself instead of opening multiple stacked widgets on the homescreen?

**Comment by diimaan** [comment]
I keep very minimal widgets. Just my continue watching/Up Next trakt lists with genre or networks depend on Movie or Shows page. 
I would understand if it is a complex work to get it added in the skin :)

**Comment by ivarbrandt** [comment]
I understand. I'm sure I could figure out how to do it. But I don't see how it would be of much use so I'm gonna say no this this request.
