### ISSUE TITLE
[Feature Question/Request] Network indicators

### ISSUE THREAD

**Issue by digitalbarrito** [ivarbrandt/skin.fentastic#85]
Not sure how feasible this is or if it's even a skin-related question/request, but when I first started my Kodi journey I used Seren with Arctic Horizon 2, but wound up using FEN/FENLite + Fentastic, because it's been a far superior experience overall. 

One of the very few things I miss from that particular setup are the Network indicators. These are little icons for whatever particular service(s) something was available like Netflix, Hulu, Google Store, etc.. This was incredibly useful to quickly sus out if something you were looking at even has a home/streaming release yet. 

Here's an example of a released movie that's available on multiple platforms from my old Seren + AH2 setup:
![Screenshot 2023-03-25 181536](https://github.com/ivarbrandt/skin.fentastic/assets/641751/e0ca1c46-3076-42ed-aa7d-b18058653d03)

And here's one of an unreleased movie that doesn't have any platforms:
![Screenshot 2023-03-25 222919](https://github.com/ivarbrandt/skin.fentastic/assets/641751/54d2e390-3832-453d-9097-3ca5231f12c4)

I'm not sure if this is something you could (or even want) to implement, it's not a critical feature to have by any means, it just saves a bit of work when browsing and is something I think plenty of folks would appreciate, even potentially as an off by default option. 

Either way, appreciate all the work you put into Fentastic and I hope you have a wonderful holiday season!

**Comment by ivarbrandt** [comment]
This would require implementation of the TMDb API and that's something that is more than I want to take on at this time. 

Thanks for your request and happy holidays :)
