### ISSUE TITLE
IMPORTANT: Kodi Omega Information

### ISSUE THREAD

**Issue by ivarbrandt** [ivarbrandt/skin.fentastic#86]
As of any version after Kodi 21 beta 2, FENtastic will break. Simple as that. You'll need to bump the ABI from 5.16.0 to 5.17.0.

If you don't know how to do this I've attached a version of FENtastic that should work with Omega moving forward. I say should because I am not on Omega myself and I wont be until there is stable release. This means after RC1, RC2 etc. Please keep in mind that this is a temporary fix and FENtastic will not get updates for Omega until I move the repository over to that. This being said, when I move FENtastic to Omega in the future, this will break compatibility with Nexus. I've decided to go about it this way because I don't want to have separate branches of the skin and be back porting changes over and over again until the branches diverge so much that I would end compatibility with Nexus anyways for my own sanity.

**What this means for Nexus users:** Nothing yet. Go about your day. FENtastic will continue to receive updates and you'll continue to be able to update it directly within Kodi like normal. Keep in mind though that when a stable version of Omega comes out I will end compatibility with Nexus. At that point you'll have update to Omega to continue to receive updates.

**What this means for Omega beta 2+ users:** Attached you'll find a version of FENtastic that should work on Omega. You won't get updates for the skin until I move the repo over to Omega which will happen after there is a stable release. If you run into any issues with the attached version please let me know.

EDIT: I've added in the helper for convenience. Make sure to install the helper first before you install the skin.

[script.fentastic.helper.zip](https://github.com/ivarbrandt/skin.fentastic/files/14394668/script.fentastic.helper.zip)
[skin.fentastic.zip](https://github.com/ivarbrandt/skin.fentastic/files/13758446/skin.fentastic.zip)

**Comment by Better-Red** [comment]
Thank you!

**Comment by TwilightMercy** [comment]
Thanks friend!
Also waiting for announcement issue for "Nimbus" skin (only saw the new WIP repositories : ) )

**Comment by ivarbrandt** [comment]
> Also waiting for announcement issue for "Nimbus" skin

It will probably never be officially announced. It's just something I'm working on for me.

**Comment by SoreTissue** [comment]
Hi. I tried installing that zip file with omega beta 2 some time ago and couldn’t get it to work. It just displayed a blank screen and my only option was to reinstall kodi. I presumed others would have tried the zip file by now and had similar issue but no one has commented so I’m presuming something went wrong on my end. You stated if anyone runs into issues to let you know so I thought I’d just put this out there. Sorry I didn’t think to grab a log file as I thought someone else would of had similar issue who had more expertise than I.

Device: Nvidia Shield Tv Pro 2019 

I first tried updating my omega version of kodi (was running nightly versions without issue) to the beta 2 nightly version which broke fentastic so I tried your zip file but it just displayed blank screen.

I then did a fresh install of kodi omega beta 2 downloaded from the prerelease tab. Without adding anything or changing any setting I tried installing your zip file but once again blank screen. At that point I just deleted kodi and then installed a fresh install of a nightly build before beta 2 broke fentastic and did my normal setup and haven’t tried since.

**Comment by ivarbrandt** [comment]
As far as I know, Omega beta 2 works with the version of FENtastic that is in the repo. You don't need the zip.

**Comment by Better-Red** [comment]
> Hi. I tried installing that zip file with omega beta 2 some time ago and couldn’t get it to work. It just displayed a blank screen and my only option was to reinstall kodi. I presumed others would have tried the zip file by now and had similar issue but no one has commented so I’m presuming something went wrong on my end. You stated if anyone runs into issues to let you know so I thought I’d just put this out there. Sorry I didn’t think to grab a log file as I thought someone else would of had similar issue who had more expertise than I.

The zip works fine for me with Kodi 21.0 Omega Beta 2 on my Windows 11 PC and with a fork of 21.0 Omega Beta 2 on my 2017 Shield.

**Comment by sherlockholmes77777** [comment]
Is skin.fentastic.zip supposed to work on Android TV? Gives error on my android tv.

**Comment by ivarbrandt** [comment]
Yes, it works on all Kodi installs using Omega beta 2+.

**Comment by sherlockholmes77777** [comment]
I get the error "the dependency on script.fentastic.helper version 0.0.0 could not be satisfied" on Omega beta 2 build.

**Comment by matthius7** [comment]
Tried using above zip on Chromecast 4k omega beta 3. Failed to install add-on from zip file. Failed to install a dependency. 2/15/24

**Comment by Sunseng** [comment]
Yes same error with me. Working good on omega b2, uncompatible on omega b3, and kicked back to default estuary skin.

**Comment by ivarbrandt** [comment]
Make sure you install the helper before attempting to install the skin.

**Comment by Sunseng** [comment]
The helper already installed from omega b2. And fentastic already have gui version 5.17.0 in there. But kodi keep saying fentastic not compatible with this kodi version (omega beta 3)

Trying to install the skin and helper again from zip file, helper succesfully updated, but skin failed due to an invalid structure.

Btw the fentastic skin is missing from  your repo, cant see it anywhere in your repo anymore🙏

**Comment by Sunseng** [comment]
Damn, my bad. My zip file must be corrupted. Download again the zip file from your github and change the version to 5.17.0 and its installed fine and working now

Thank you very much 🙏👍😁

**Comment by dannysporea** [comment]
Trying to install it on clean omega b3, the helper is not showing in the repository and cannot be installed. The skin fails to install from the zip file due to a missing dependency (the fentastic helper). Is there a way to install the helper on b3? Thank you

**Comment by matthius7** [comment]
> Trying to install it on clean omega b3, the helper is not showing in the repository and cannot be installed. The skin fails to install from the zip file due to a missing dependency (the fentastic helper). Is there a way to install the helper on b3? Thank you

https://github.com/ivarbrandt/script.fentastic.helper flash this first then above Fentastic zip. Btw beta 3 is buggy af. Better to wait for update to stable omega but up to you. I've been on it and went back to 20.3 lots and lots of bugs that weren't present on beta 2

**Comment by ivarbrandt** [comment]
I've added the helper to the first comment.

**Comment by ivarbrandt** [comment]
> So I've just installed it the other day and the first bug i found was that the custom widgets and menus don't work on omega (Google TV).

> So for anyone just seeing a blank screen reset main menu items and it should work👍

I'm confused. Does it work or not?

**Comment by matthius7** [comment]
I've always had to remake menus everytime I've ever set up Fentastic. Didn't matter if it was on Omega or Nexus or Matrix

**Comment by ivarbrandt** [comment]
> I've always had to remake menus everytime I've ever set up Fentastic.

Every time?

**Comment by matthius7** [comment]
> > I've always had to remake menus everytime I've ever set up Fentastic.
> 
> Every time?

For the initial first time after installing ; yes I believe so.

**Comment by ivarbrandt** [comment]
Is that just something you got used to doing or do you need to do it to get the widgets to work?

**Comment by matthius7** [comment]
> Is that just something you got used to doing or do you need to do it to get the widgets to work?

Something I got used to doing. So the movie and TV show category is already there.

**Comment by ivarbrandt** [comment]
Yeah that's normal. Because it isn't installed from the repo. But did this happen on Nexus when downloaded straight from the repo?

**Comment by matthius7** [comment]
> Yeah that's normal. Because it isn't installed from the repo. But did this happen on Nexus when downloaded straight from the repo?

No. Makes the categories automatically

**Comment by ivarbrandt** [comment]
Whew. I thought so. Alright thanks :)

**Comment by marcos28102002** [comment]
> > So I've just installed it the other day and the first bug i found was that the custom widgets and menus don't work on omega (Google TV).
> 
> > So for anyone just seeing a blank screen reset main menu items and it should work👍
> 
> I'm confused. Does it work or not?
> 

Yeah it does work but just a heads up for some folks that try to install this. For example if you would install and get the blank screen on kodi because you didn't reset from previous install. And it's on a TV you can't get access to the settings, so maybe someone than thinks it needs a full reinstall but that isn't the case. Sorry for the confusion🙏

**Comment by toddlewis1990** [comment]
Hi. I really love this skin, thanks for your hard work in creating it. Is there a way to get the helper script to run on webOS? I’m trying to do it but I’ve been unsuccessful and I’m not 100% sure what URL I’m supposed to be entering in file manager (or if it can even be done that way). Appreciate the help.

**Comment by ivarbrandt** [comment]
You can download the helper from the first post then install from zip.

**Comment by toddlewis1990** [comment]
Forgive me as me I’m not particularly well-versed in this sort of thing. What URL do I need to enter into File Manager?

**Comment by matthius7** [comment]
> Forgive me as me I’m not particularly well-versed in this sort of thing. What URL do I need to enter into File Manager?

You don't enter any URL. Download the two above zips. Transfer them to your internal storage in Kodi. Go to add-ons in Kodi. Flash zip. Starting with Fentastic helper then the skin. Switch to skin and profit.

**Comment by toddlewis1990** [comment]
I have no idea how to do that with webOS.

**Comment by ivarbrandt** [comment]
> I have no idea how to do that with webOS.

I understand. What you need to do is find a way to put those two zips on your device. Then you can install from zip inside of Kodi. If you don't know how to do this, wait till FENtastic is updated to work with Omega. You'll be able to use the file manager URL to install it then.

**Comment by toddlewis1990** [comment]
I’ll try that. Thanks very much for your help,

**Comment by ivarbrandt** [comment]
> I’ll try that. Thanks very much for your help,

You're welcome. I know that tech can be daunting because it is unfamiliar, but you can do it. There's tons of resources out there that you can find on Google to learn how to do all sorts of things including tech related stuff. Good luck! :)

**Comment by toddlewis1990** [comment]
> > I’ll try that. Thanks very much for your help,
> 
> You're welcome. I know that tech can be daunting because it is unfamiliar, but you can do it. There's tons of resources out there that you can find on Google to learn how to do all sorts of things including tech related stuff. Good luck! :)

Your idea worked! I found a spare USB stick in my drawer, and found the contents in Kodi. Went off without a hitch. Thanks once again. WebOS struggles to get on with Kodi, but you’re lightweight, straight-forward skin makes it work. Appreciate it!

**Comment by ivarbrandt** [comment]
> Went off without a hitch.

So awesome to hear. Congrats on figuring it out!

**Comment by cerinthus** [comment]
Won't install on kodi for xbox.  Just crashes to black screen.  Worked fine before the Omega update

**Comment by ivarbrandt** [comment]
> Won't install on kodi for xbox. Just crashes to black screen. Worked fine before the Omega update

Ok. The more info you give me the more likely I will be able to help you resolve your issue.

**Comment by cerinthus** [comment]
> > Won't install on kodi for xbox. Just crashes to black screen. Worked fine before the Omega update
> 
> Ok. The more info you give me the more likely I will be able to help you resolve your issue.

Of course. Unfortunately that was all the info I had. If I tried install the zip on Kodi it went to black screen.

I fixed it by removing settings.xml installating the add-on, and then restoring the settings.xml

Not sure if that helps you at all. The existing settings worked fine, but it wouldn't install if they were there

**Comment by ivarbrandt** [comment]
Thank you. The settings reset is something I would not have thought of. I'm glad you were able to figure it out.

**Comment by npmstart-pray** [comment]
How is work coming on an update for Omega?

**Comment by matthius7** [comment]
> How is work coming on an update for Omega?

When the newest updated version for Omega is ready it will be able to be installed normally through Ivar's GitHub. Until then ; the above version works perfectly on stable Omega.

**Comment by Omarscomin** [comment]
> How is work coming on an update for Omega?  

It was officially released...like...5 seconds ago. Why make him feel pressured, especially when he's already provided zips for a version of FENtastic that works with Omega?

**Comment by npmstart-pray** [comment]
Smh It was not a passive-aggressive attempt to pressure anyone into delivering faster/sooner. I was just asking if there was an anticipated date for an update. Key word being IF. Sent from my latest communicator device somewhere in space. On Apr 7, 2024, at 12:06, Omarscomin ***@***.***> wrote:﻿

How is work coming on an update for Omega?

It was officially released...like...5 seconds ago. Why make him feel pressured, especially when he's already provided zips for a version of FENtastic that works with Omega?

**Comment by Omarscomin** [comment]
> I was just asking if there was an anticipated date for an update. Key word being IF.

@npmstart-pray that's....not what you said, but alrighty :)

As I already stated, the developer has provided zips files for a version of FENtastic that works with Omega. Not sure why you're so opposed to using them.

**Comment by GNUzziHub** [comment]
Hi, hi hi.  
Big fan of your work.
Is there a way to download these things for Kodi on a TV? There's no packages on the Github.

**Comment by hpsxrb** [comment]
I'm on Windows 11 with Kodi v21 Omega (x64) installed and when I close the application, kodi.exe continues running!

**Comment by ivarbrandt** [comment]
> How is work coming on an update for Omega?

I just started working on Omega compatibility. No ETA yet on when I'll have an update for the main repo. 

If you just can't wait, there is test version ` 1.0.23a` in my test repo. This will work on Omega straight from the repo but please keep in mind that the ONLY thing that has been changed is the GUI version to allow for Omega compatibility. I still need to update other parts of it so it's up to date with all the changes made in Omega.

**Comment by CircaOwl** [comment]
You are the greatest, can’t wait! My setups thank you!

**Comment by TwilightMercy** [comment]
Does bumping gui version to 5.17.0 breaks support for Nexus?

**Comment by Arthur1967** [comment]
It’s working good for me too thank you for the work you put in

**Comment by ivarbrandt** [comment]
> Does bumping gui version to 5.17.0 breaks support for Nexus?

Yes it does.

**Comment by afda1** [comment]
This probably not the best place to ask but I've had to reinstall Kodi on my TV, I wanted to re-install this skin as well. Once I've added this repository to my Kodi I can only install the sounds pack from this repository. There is no option for the skin...

Weird thing is that I've installed Kodi on my PC and done the same thing and this time I can see the skin in the repository. Both instances are running Kodi Omega...

Does anyone have any ideas how I can fix this?

**Comment by Omarscomin** [comment]
> This probably not the best place to ask but I've had to reinstall Kodi on my TV, I wanted to re-install this skin as well. Once I've added this repository to my Kodi I can only install the sounds pack from this repository. There is no option for the skin...
> 
> Weird thing is that I've installed Kodi on my PC and done the same thing and this time I can see the skin in the repository. Both instances are running Kodi Omega...
> 
> Does anyone have any ideas how I can fix this?

@afda1 did you read the post?

**Comment by afda1** [comment]
> > This probably not the best place to ask but I've had to reinstall Kodi on my TV, I wanted to re-install this skin as well. Once I've added this repository to my Kodi I can only install the sounds pack from this repository. There is no option for the skin...
> > Weird thing is that I've installed Kodi on my PC and done the same thing and this time I can see the skin in the repository. Both instances are running Kodi Omega...
> > Does anyone have any ideas how I can fix this?
> 
> @afda1 did you read the post?

I did, it says that Omega is not fully compatible but why is the skin showing up on my Kodi on PC but not on my Kodi on TV both of which are **Omegas**?

I've also wanted to install the Nimbus skin from this same developer but couldn't figure out how either as it doesn't show as installable either.

**Comment by Better-Red** [comment]
> > > This probably not the best place to ask but I've had to reinstall Kodi on my TV, I wanted to re-install this skin as well. Once I've added this repository to my Kodi I can only install the sounds pack from this repository. There is no option for the skin...
> > > Weird thing is that I've installed Kodi on my PC and done the same thing and this time I can see the skin in the repository. Both instances are running Kodi Omega...
> > > Does anyone have any ideas how I can fix this?
> > 
> > 
> > @afda1 did you read the post?
> 
> I did, it says that Omega is not fully compatible but why is the skin showing up on my Kodi on PC but not on my Kodi on TV both of which are **Omegas**?
> 
> I've also wanted to install the Nimbus skin from this same developer but couldn't figure out how either as it doesn't show as installable either.

@afda1, please re-read the first post in this thread. I've no idea how FENtastic is showing in the repo on Omega. Maybe you've managed to disable hide incompatible or it's an old prerelease.

**Comment by afda1** [comment]
> > > > This probably not the best place to ask but I've had to reinstall Kodi on my TV, I wanted to re-install this skin as well. Once I've added this repository to my Kodi I can only install the sounds pack from this repository. There is no option for the skin...
> > > > Weird thing is that I've installed Kodi on my PC and done the same thing and this time I can see the skin in the repository. Both instances are running Kodi Omega...
> > > > Does anyone have any ideas how I can fix this?
> > > 
> > > 
> > > @afda1 did you read the post?
> > 
> > 
> > I did, it says that Omega is not fully compatible but why is the skin showing up on my Kodi on PC but not on my Kodi on TV both of which are **Omegas**?
> > I've also wanted to install the Nimbus skin from this same developer but couldn't figure out how either as it doesn't show as installable either.
> 
> @afda1, please re-read the first post in this thread. I've no idea how FENtastic is showing in the repo on Omega. Maybe you've managed to disable hide incompatible or it's an old test release of Kodi.

Going a bit off-topic here but how do I install the Nimbus skin from ivarbrandt while we wait for Fentastic to be compatible with Omega?

I just need a lightweight skin is all...

**Comment by Better-Red** [comment]
@afda1, there's a download link for FENtastic for Omega in the opening post. Install as zip files, script.fentastic.helper first, then skin.fentastic. Works great.

**Comment by ivarbrandt** [comment]
> Weird thing is that I've installed Kodi on my PC and done the same thing and this time I can see the skin in the repository.

The only way this is possible is if you have the main repo installed on your TV vs the test repo on your PC.

> Going a bit off-topic here but how do I install the Nimbus skin from ivarbrandt while we wait for Fentastic to be compatible with Omega?

Nimbus is in the test repo. Keep in mind it's still under development.

**Comment by ivarbrandt** [comment]
That's brave lol. I've never tried that.

It affects which versions of Kodi the skin can be installed on. As changes are made to the skinning engine, some changes cannot be back ported to previous versions of Kodi so they make the skinsinstallable only on the most recent version of Kodi that contains the skinning changes by bumping the GUI version.

**Comment by TwilightMercy** [comment]
> That's brave lol. I've never tried that.
> 
> It affects which versions of Kodi the skin can be installed on. As changes are made to the skinning engine, some changes cannot be back ported to previous versions of Kodi so they make the skins installable only on the most recent version of Kodi that contains the skinning changes by bumping the GUI version.

I see. After I've commented, the latest skin version works perfectly and the same both for Nexus and Omega.
Does it probably mean that no significant changes were made between Kodi's GUI versions? (because it works OK for both when GUI version not specified in addon.xml)

**Comment by TwilightMercy** [comment]
And another question, 
beside bumping GUI version to 5.17.0 in FENtastic addon.xml (which works good on Omega) - Do you plan to do more changes/compatibility updates to the skin? (If needed to Omega)

**Comment by ivarbrandt** [comment]
Not exactly. 

By commenting out the GUI version you make it work on both Kodi versions. This can cause some problems though if the skin contains code that is specific to one version of Kodi. 

And yes, I am working on implementing the changes made in the skinning engine for Omega.

**Comment by Shrek-SC** [comment]
Hi Ivarbrandt, I have a question regarding the test version.

If I'm using the version of Fentastic from the test repo on Omega, will the settings carry across the over to the new Omega update once it is ready, or will I need to set it all up again?

**Comment by ivarbrandt** [comment]
All of your settings, widgets, etc will carry over. The only thing that will change is that it will receive updates from the main repo in the future rather than the test repo.

**Comment by averythelabel** [comment]
Hello!

I've done the helper zip, then the skin, but I'm still only able to load the sounds and no skin. This is on a 4k Firestick with Kodi 21, no beta installed. 

Any tips?

**Comment by matthius7** [comment]
Yay. At work but guessing it's in main repo now since you closed the issue. !! Whoop whoop

**Comment by ivarbrandt** [comment]
Correct. FENtastic and Nimbus are both in the main repo now.
