### ISSUE TITLE
Widgets doesn't refresh when I open Kodi

### ISSUE THREAD

**Issue by levider** [ivarbrandt/skin.fentastic#87]
Hello,
my issue with fentastic skin is that when I open Kodi then widgets doesn't load and it looks like this:
![Zrzut ekranu 2023-12-28 135953](https://github.com/ivarbrandt/skin.fentastic/assets/28191531/f916791b-7cf0-4253-a590-8a1948f28c65)
I have to "reload skin" to make it work
Any way to fix?
Maybe automatically force reload skin after some time?

Kodi v20
Windows 10 (i think the same on android tv)
Fentastic 1.0.23

**Comment by ivarbrandt** [comment]
Are you using Fen Light?

**Comment by levider** [comment]
No, just Fen. Forgot to mention

**Comment by Tikipeter** [comment]
Please report this issue to my github.

It is not skin related.

**Comment by ivarbrandt** [comment]
I've seen this happen with Fen Light but that was a version or two ago. I've never seen it happen with Fen.

Like Peter said, please report this to his Github because this isn't a skin issue.
