### ISSUE TITLE
Viewtype not being saved

### ISSUE THREAD

**Issue by Glx28** [ivarbrandt/skin.fentastic#88]
I can't seem to find a way to permanently save my changes for the viewtype in kodi 20.2, it always reverts back after exiting the menu.

**Comment by Tikipeter** [comment]
Unless you're using Kodi with a library, then this isn't a skin issue.

Set the view types you want within the addon/s you are using.

**Comment by ivarbrandt** [comment]
Yup. What he said ⬆️
