### ISSUE TITLE
Adding Skin Repository to URL to README's

### ISSUE THREAD

**Issue by TwilightMercy** [ivarbrandt/skin.FENtastic#9]
Hi (sorry for spamming issues for different subjects, loving your skin)

Is it possible to add in these README's in Github:
https://github.com/ivarbrandt/repository.ivarbrandt#readme
https://github.com/ivarbrandt/skin.FENtastic#readme

The URL for the repository to configure in Kodi File Manager?
https://ivarbrandt.github.io/repository.ivarbrandt/

Currently it's available to find by clicking on Environments in **repository.ivarbrandt**:

![image](https://user-images.githubusercontent.com/29895680/229301607-7eaacb5f-daa5-45a9-b8f1-5ac427167f9d.png)

Thank you very much!

**Comment by ivarbrandt** [comment]
Ah yes I was planning on adding it to this repo. 

Thanks for reminding me.
