### ISSUE TITLE
Add a wat yo add local path for Main Menu (Feature Request)

### ISSUE THREAD

**Issue by TahaUNAL** [ivarbrandt/skin.fentastic#91]
Hello. First of all, I love the Fentastic skin and I realize that the main purpose of the skin is to be used in conjunction with the Fen add-on. However, my only purpose for using Kodi is to watch movies that I add to my local server at home. So is it possible to add a local path to the main menu paths? Congratulations for the great skin and best of luck for your future projects

**Comment by ivarbrandt** [comment]
I apologize it took me awhile to respond.

Implementing library widgets back into the skin would require an overhaul of the widget management system. That's something I don't want to take on at this time.
