### ISSUE TITLE
OSD Question

### ISSUE THREAD

**Issue by derrgoo** [ivarbrandt/skin.fentastic#92]
I am wondering is there is a setting that will show full OSD always. If not can I request a choice. 🙏

![image](https://github.com/ivarbrandt/skin.fentastic/assets/63697905/249219de-3c69-4409-a54d-7c7194a32b57)

**Comment by ivarbrandt** [comment]
I'm leaning towards no but lemme think on it.

**Comment by TwilightMercy** [comment]
Isn’t it that setting?


![Uploading image.png…]()

**Comment by derrgoo** [comment]
@TwilightMercy not the same that is how long it stays open but I want to see a more detailed look like when you press information.

**Comment by dinjojo** [comment]
Yes I'm also looking for same to show media flags of the video playing and if possible show ratings as well

**Comment by ivarbrandt** [comment]
I apologize it took me so long to respond. I've decided no on this.

**Comment by dinjojo** [comment]
Thanks is it cause of performance hit?

**Comment by ivarbrandt** [comment]
Nah I just don't want to do it.
