### ISSUE TITLE
Support for episode type label

### ISSUE THREAD

**Issue by umbrellaplug** [ivarbrandt/skin.fentastic#94]
Would it be possible to add support for episode_type into Fentastic? Jurial recently did it with Fuse and it's a pretty nice feature in my opinion and I'd love to see it in Fentastic also. Both Fen and Umbrella have support for this. He's showing a label on posters for premier/ finale on posters. I'll attach a screenshot.

![image](https://github.com/ivarbrandt/skin.fentastic/assets/107957815/29d65058-bef7-4e40-96b0-2ca656277ed8)

**Comment by ivarbrandt** [comment]
Hey dude! Great to hear form ya. How are you doing?

That's pretty cool. I'm not seeing the functionality/point though. Here's why:

If the episode is the last one in a container that is a season of course it is the season finale. Mid-season premiers and finales are characterized by longer than average time spans between aired episodes. All of this can be seen visually without this feature.

I'm genuinely curious, what is your perspective on this?

**Comment by umbrellaplug** [comment]
My thought process was for widgets using episodes like "Progress Episodes". Go ahead and close this request out. I'll take care of adding it into my personal skin I run. Thanks!
