### ISSUE TITLE
(Request) widget amount

### ISSUE THREAD

**Issue by derrgoo** [ivarbrandt/skin.fentastic#97]
Another request 😀 

Is it possible to add in settings to choose amount of posters on a widget line. I use pignate on some add ons but some don't have that so sometimes a widget can consist of 100 which kills loading time. Have a think 🤔 and let me know if this is possible. Thanks. 🙏

**Comment by ivarbrandt** [comment]
It is possible but I removed it in an earlier version of the skin because it doesn't have an effect on actual loading times. This needs to be controlled by the addon.

**Comment by derrgoo** [comment]
The other reason is just organizing the widget to show first updated movies like 10-20 instead of the huge widget list. Not all addons have pignet options. In omega when it comes final it also has built in click to see the full widget. So I just thought that would be useful as other skins have. If not maybe just show the code I can copy and paste it in if that's not too hard.

**Comment by ivarbrandt** [comment]
I don't think you're understanding me. Even if I did add an option to set the widget limit, it wouldn't make **ANY** difference as that needs to be controlled by the addon.

As for Omega I don't know anything about that yet. I'm still on Nexus and will be until a stable release of Omega becomes available.

**Comment by derrgoo** [comment]
I totally understand what you're saying but skin can control the size of the widget because there are countless skins that have this feature. Let's say your using an add on that doesn't have built in pignet so skin like fuse or h2 or others have a setting. Therefore, if you say 10 it stops at 10 but currently with nexus there would be no next button and you must goto addon to get more. (That is fine) omega as I do not use as my daily driver have tested that it allows for any list that is short to have a next button automatic. So speed is secondary but primary is just having smaller lists with addons that don't have it built in. However, I can see you don't care which is your skin and I respect your decision.

**Comment by ivarbrandt** [comment]
> I totally understand what you're saying but skin can control the size of the widget because there are countless skins that have this feature

Yes but controlling the widget limit through the skin is only effective for library items. If you have a widget from an addon that has 100 items in it and the widget limit for the skin is set to 20, then yes it will display 20 items. **BUT,** because the addon itself is still loading 100 items for that widget, all 100 items will be loaded even if you can only see 20. This is why I say that adding in a widget limit through the skin is **USELESS** for addons.

**Comment by derrgoo** [comment]
That makes sense. I never looked at it that way. So if you choose 20 you will have 100 fanart in cache? I use a shield so never really thought about memory issues. But appreciate your response. I learn everyday.

**Comment by ivarbrandt** [comment]
Yes, this is why I say that changing the widget limit through the skin won't make any difference in loading speed for the widgets. It has to be controlled through the addon.
